/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetVirtualMachineFileSystemInformationResponseContent struct for GetVirtualMachineFileSystemInformationResponseContent
type GetVirtualMachineFileSystemInformationResponseContent struct {
	Data GetFsInfoResult `json:"data"`
}

// NewGetVirtualMachineFileSystemInformationResponseContent instantiates a new GetVirtualMachineFileSystemInformationResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVirtualMachineFileSystemInformationResponseContent(data GetFsInfoResult) *GetVirtualMachineFileSystemInformationResponseContent {
	this := GetVirtualMachineFileSystemInformationResponseContent{}
	this.Data = data
	return &this
}

// NewGetVirtualMachineFileSystemInformationResponseContentWithDefaults instantiates a new GetVirtualMachineFileSystemInformationResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVirtualMachineFileSystemInformationResponseContentWithDefaults() *GetVirtualMachineFileSystemInformationResponseContent {
	this := GetVirtualMachineFileSystemInformationResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *GetVirtualMachineFileSystemInformationResponseContent) GetData() GetFsInfoResult {
	if o == nil {
		var ret GetFsInfoResult
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetVirtualMachineFileSystemInformationResponseContent) GetDataOk() (*GetFsInfoResult, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetVirtualMachineFileSystemInformationResponseContent) SetData(v GetFsInfoResult) {
	o.Data = v
}

func (o GetVirtualMachineFileSystemInformationResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetVirtualMachineFileSystemInformationResponseContent struct {
	value *GetVirtualMachineFileSystemInformationResponseContent
	isSet bool
}

func (v NullableGetVirtualMachineFileSystemInformationResponseContent) Get() *GetVirtualMachineFileSystemInformationResponseContent {
	return v.value
}

func (v *NullableGetVirtualMachineFileSystemInformationResponseContent) Set(val *GetVirtualMachineFileSystemInformationResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVirtualMachineFileSystemInformationResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVirtualMachineFileSystemInformationResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVirtualMachineFileSystemInformationResponseContent(val *GetVirtualMachineFileSystemInformationResponseContent) *NullableGetVirtualMachineFileSystemInformationResponseContent {
	return &NullableGetVirtualMachineFileSystemInformationResponseContent{value: val, isSet: true}
}

func (v NullableGetVirtualMachineFileSystemInformationResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVirtualMachineFileSystemInformationResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


