/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAccessControlListResponseContent struct for GetAccessControlListResponseContent
type GetAccessControlListResponseContent struct {
	Data []AccessControlSummary `json:"data"`
}

// NewGetAccessControlListResponseContent instantiates a new GetAccessControlListResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccessControlListResponseContent(data []AccessControlSummary) *GetAccessControlListResponseContent {
	this := GetAccessControlListResponseContent{}
	this.Data = data
	return &this
}

// NewGetAccessControlListResponseContentWithDefaults instantiates a new GetAccessControlListResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccessControlListResponseContentWithDefaults() *GetAccessControlListResponseContent {
	this := GetAccessControlListResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *GetAccessControlListResponseContent) GetData() []AccessControlSummary {
	if o == nil {
		var ret []AccessControlSummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAccessControlListResponseContent) GetDataOk() ([]AccessControlSummary, bool) {
	if o == nil {
    return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetAccessControlListResponseContent) SetData(v []AccessControlSummary) {
	o.Data = v
}

func (o GetAccessControlListResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccessControlListResponseContent struct {
	value *GetAccessControlListResponseContent
	isSet bool
}

func (v NullableGetAccessControlListResponseContent) Get() *GetAccessControlListResponseContent {
	return v.value
}

func (v *NullableGetAccessControlListResponseContent) Set(val *GetAccessControlListResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccessControlListResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccessControlListResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccessControlListResponseContent(val *GetAccessControlListResponseContent) *NullableGetAccessControlListResponseContent {
	return &NullableGetAccessControlListResponseContent{value: val, isSet: true}
}

func (v NullableGetAccessControlListResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccessControlListResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


