/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateLVMResponseContent struct for CreateLVMResponseContent
type CreateLVMResponseContent struct {
	Data string `json:"data"`
}

// NewCreateLVMResponseContent instantiates a new CreateLVMResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLVMResponseContent(data string) *CreateLVMResponseContent {
	this := CreateLVMResponseContent{}
	this.Data = data
	return &this
}

// NewCreateLVMResponseContentWithDefaults instantiates a new CreateLVMResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLVMResponseContentWithDefaults() *CreateLVMResponseContent {
	this := CreateLVMResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *CreateLVMResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateLVMResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateLVMResponseContent) SetData(v string) {
	o.Data = v
}

func (o CreateLVMResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateLVMResponseContent struct {
	value *CreateLVMResponseContent
	isSet bool
}

func (v NullableCreateLVMResponseContent) Get() *CreateLVMResponseContent {
	return v.value
}

func (v *NullableCreateLVMResponseContent) Set(val *CreateLVMResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLVMResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLVMResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLVMResponseContent(val *CreateLVMResponseContent) *NullableCreateLVMResponseContent {
	return &NullableCreateLVMResponseContent{value: val, isSet: true}
}

func (v NullableCreateLVMResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLVMResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


