/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListDirectoriesResponseContent struct for ListDirectoriesResponseContent
type ListDirectoriesResponseContent struct {
	Data []DirectorySummary `json:"data"`
}

// NewListDirectoriesResponseContent instantiates a new ListDirectoriesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDirectoriesResponseContent(data []DirectorySummary) *ListDirectoriesResponseContent {
	this := ListDirectoriesResponseContent{}
	this.Data = data
	return &this
}

// NewListDirectoriesResponseContentWithDefaults instantiates a new ListDirectoriesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDirectoriesResponseContentWithDefaults() *ListDirectoriesResponseContent {
	this := ListDirectoriesResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListDirectoriesResponseContent) GetData() []DirectorySummary {
	if o == nil {
		var ret []DirectorySummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListDirectoriesResponseContent) GetDataOk() ([]DirectorySummary, bool) {
	if o == nil {
    return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListDirectoriesResponseContent) SetData(v []DirectorySummary) {
	o.Data = v
}

func (o ListDirectoriesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableListDirectoriesResponseContent struct {
	value *ListDirectoriesResponseContent
	isSet bool
}

func (v NullableListDirectoriesResponseContent) Get() *ListDirectoriesResponseContent {
	return v.value
}

func (v *NullableListDirectoriesResponseContent) Set(val *ListDirectoriesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListDirectoriesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListDirectoriesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDirectoriesResponseContent(val *ListDirectoriesResponseContent) *NullableListDirectoriesResponseContent {
	return &NullableListDirectoriesResponseContent{value: val, isSet: true}
}

func (v NullableListDirectoriesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDirectoriesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


