/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the ShutdownVirtualMachineResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShutdownVirtualMachineResponseContent{}

// ShutdownVirtualMachineResponseContent struct for ShutdownVirtualMachineResponseContent
type ShutdownVirtualMachineResponseContent struct {
	Data string `json:"data"`
}

// NewShutdownVirtualMachineResponseContent instantiates a new ShutdownVirtualMachineResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShutdownVirtualMachineResponseContent(data string) *ShutdownVirtualMachineResponseContent {
	this := ShutdownVirtualMachineResponseContent{}
	this.Data = data
	return &this
}

// NewShutdownVirtualMachineResponseContentWithDefaults instantiates a new ShutdownVirtualMachineResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShutdownVirtualMachineResponseContentWithDefaults() *ShutdownVirtualMachineResponseContent {
	this := ShutdownVirtualMachineResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ShutdownVirtualMachineResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ShutdownVirtualMachineResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ShutdownVirtualMachineResponseContent) SetData(v string) {
	o.Data = v
}

func (o ShutdownVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShutdownVirtualMachineResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableShutdownVirtualMachineResponseContent struct {
	value *ShutdownVirtualMachineResponseContent
	isSet bool
}

func (v NullableShutdownVirtualMachineResponseContent) Get() *ShutdownVirtualMachineResponseContent {
	return v.value
}

func (v *NullableShutdownVirtualMachineResponseContent) Set(val *ShutdownVirtualMachineResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableShutdownVirtualMachineResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableShutdownVirtualMachineResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShutdownVirtualMachineResponseContent(val *ShutdownVirtualMachineResponseContent) *NullableShutdownVirtualMachineResponseContent {
	return &NullableShutdownVirtualMachineResponseContent{value: val, isSet: true}
}

func (v NullableShutdownVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShutdownVirtualMachineResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


