/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// AccessControlSummary struct for AccessControlSummary
type AccessControlSummary struct {
	Path string `json:"path"`
	// The role id
	Roleid string `json:"roleid"`
	// The user group id
	Ugid string `json:"ugid"`
	Type AccessControlType `json:"type"`
	// Allow permission propegation
	Propagate float32 `json:"propagate"`
}

// NewAccessControlSummary instantiates a new AccessControlSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessControlSummary(path string, roleid string, ugid string, type_ AccessControlType, propagate float32) *AccessControlSummary {
	this := AccessControlSummary{}
	this.Path = path
	this.Roleid = roleid
	this.Ugid = ugid
	this.Type = type_
	this.Propagate = propagate
	return &this
}

// NewAccessControlSummaryWithDefaults instantiates a new AccessControlSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessControlSummaryWithDefaults() *AccessControlSummary {
	this := AccessControlSummary{}
	return &this
}

// GetPath returns the Path field value
func (o *AccessControlSummary) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AccessControlSummary) GetPathOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AccessControlSummary) SetPath(v string) {
	o.Path = v
}

// GetRoleid returns the Roleid field value
func (o *AccessControlSummary) GetRoleid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Roleid
}

// GetRoleidOk returns a tuple with the Roleid field value
// and a boolean to check if the value has been set.
func (o *AccessControlSummary) GetRoleidOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Roleid, true
}

// SetRoleid sets field value
func (o *AccessControlSummary) SetRoleid(v string) {
	o.Roleid = v
}

// GetUgid returns the Ugid field value
func (o *AccessControlSummary) GetUgid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ugid
}

// GetUgidOk returns a tuple with the Ugid field value
// and a boolean to check if the value has been set.
func (o *AccessControlSummary) GetUgidOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Ugid, true
}

// SetUgid sets field value
func (o *AccessControlSummary) SetUgid(v string) {
	o.Ugid = v
}

// GetType returns the Type field value
func (o *AccessControlSummary) GetType() AccessControlType {
	if o == nil {
		var ret AccessControlType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessControlSummary) GetTypeOk() (*AccessControlType, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessControlSummary) SetType(v AccessControlType) {
	o.Type = v
}

// GetPropagate returns the Propagate field value
func (o *AccessControlSummary) GetPropagate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Propagate
}

// GetPropagateOk returns a tuple with the Propagate field value
// and a boolean to check if the value has been set.
func (o *AccessControlSummary) GetPropagateOk() (*float32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Propagate, true
}

// SetPropagate sets field value
func (o *AccessControlSummary) SetPropagate(v float32) {
	o.Propagate = v
}

func (o AccessControlSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["path"] = o.Path
	}
	if true {
		toSerialize["roleid"] = o.Roleid
	}
	if true {
		toSerialize["ugid"] = o.Ugid
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["propagate"] = o.Propagate
	}
	return json.Marshal(toSerialize)
}

type NullableAccessControlSummary struct {
	value *AccessControlSummary
	isSet bool
}

func (v NullableAccessControlSummary) Get() *AccessControlSummary {
	return v.value
}

func (v *NullableAccessControlSummary) Set(val *AccessControlSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessControlSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessControlSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessControlSummary(val *AccessControlSummary) *NullableAccessControlSummary {
	return &NullableAccessControlSummary{value: val, isSet: true}
}

func (v NullableAccessControlSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessControlSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


