/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the CreateClusterConfigRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClusterConfigRequestContent{}

// CreateClusterConfigRequestContent struct for CreateClusterConfigRequestContent
type CreateClusterConfigRequestContent struct {
	// Cluster name
	Clustername string `json:"clustername"`
	Link0 *string `json:"link0,omitempty"`
	Link1 *string `json:"link1,omitempty"`
	Link2 *string `json:"link2,omitempty"`
	Link3 *string `json:"link3,omitempty"`
	Link4 *string `json:"link4,omitempty"`
	Link5 *string `json:"link5,omitempty"`
	Link6 *string `json:"link6,omitempty"`
	Link7 *string `json:"link7,omitempty"`
	// Node ID for the node
	Nodeid *float32 `json:"nodeid,omitempty"`
	// Votes for the node
	Votes *float32 `json:"votes,omitempty"`
}

// NewCreateClusterConfigRequestContent instantiates a new CreateClusterConfigRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterConfigRequestContent(clustername string) *CreateClusterConfigRequestContent {
	this := CreateClusterConfigRequestContent{}
	this.Clustername = clustername
	return &this
}

// NewCreateClusterConfigRequestContentWithDefaults instantiates a new CreateClusterConfigRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterConfigRequestContentWithDefaults() *CreateClusterConfigRequestContent {
	this := CreateClusterConfigRequestContent{}
	return &this
}

// GetClustername returns the Clustername field value
func (o *CreateClusterConfigRequestContent) GetClustername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Clustername
}

// GetClusternameOk returns a tuple with the Clustername field value
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetClusternameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Clustername, true
}

// SetClustername sets field value
func (o *CreateClusterConfigRequestContent) SetClustername(v string) {
	o.Clustername = v
}

// GetLink0 returns the Link0 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink0() string {
	if o == nil || IsNil(o.Link0) {
		var ret string
		return ret
	}
	return *o.Link0
}

// GetLink0Ok returns a tuple with the Link0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink0Ok() (*string, bool) {
	if o == nil || IsNil(o.Link0) {
		return nil, false
	}
	return o.Link0, true
}

// HasLink0 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink0() bool {
	if o != nil && !IsNil(o.Link0) {
		return true
	}

	return false
}

// SetLink0 gets a reference to the given string and assigns it to the Link0 field.
func (o *CreateClusterConfigRequestContent) SetLink0(v string) {
	o.Link0 = &v
}

// GetLink1 returns the Link1 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink1() string {
	if o == nil || IsNil(o.Link1) {
		var ret string
		return ret
	}
	return *o.Link1
}

// GetLink1Ok returns a tuple with the Link1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink1Ok() (*string, bool) {
	if o == nil || IsNil(o.Link1) {
		return nil, false
	}
	return o.Link1, true
}

// HasLink1 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink1() bool {
	if o != nil && !IsNil(o.Link1) {
		return true
	}

	return false
}

// SetLink1 gets a reference to the given string and assigns it to the Link1 field.
func (o *CreateClusterConfigRequestContent) SetLink1(v string) {
	o.Link1 = &v
}

// GetLink2 returns the Link2 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink2() string {
	if o == nil || IsNil(o.Link2) {
		var ret string
		return ret
	}
	return *o.Link2
}

// GetLink2Ok returns a tuple with the Link2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink2Ok() (*string, bool) {
	if o == nil || IsNil(o.Link2) {
		return nil, false
	}
	return o.Link2, true
}

// HasLink2 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink2() bool {
	if o != nil && !IsNil(o.Link2) {
		return true
	}

	return false
}

// SetLink2 gets a reference to the given string and assigns it to the Link2 field.
func (o *CreateClusterConfigRequestContent) SetLink2(v string) {
	o.Link2 = &v
}

// GetLink3 returns the Link3 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink3() string {
	if o == nil || IsNil(o.Link3) {
		var ret string
		return ret
	}
	return *o.Link3
}

// GetLink3Ok returns a tuple with the Link3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink3Ok() (*string, bool) {
	if o == nil || IsNil(o.Link3) {
		return nil, false
	}
	return o.Link3, true
}

// HasLink3 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink3() bool {
	if o != nil && !IsNil(o.Link3) {
		return true
	}

	return false
}

// SetLink3 gets a reference to the given string and assigns it to the Link3 field.
func (o *CreateClusterConfigRequestContent) SetLink3(v string) {
	o.Link3 = &v
}

// GetLink4 returns the Link4 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink4() string {
	if o == nil || IsNil(o.Link4) {
		var ret string
		return ret
	}
	return *o.Link4
}

// GetLink4Ok returns a tuple with the Link4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink4Ok() (*string, bool) {
	if o == nil || IsNil(o.Link4) {
		return nil, false
	}
	return o.Link4, true
}

// HasLink4 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink4() bool {
	if o != nil && !IsNil(o.Link4) {
		return true
	}

	return false
}

// SetLink4 gets a reference to the given string and assigns it to the Link4 field.
func (o *CreateClusterConfigRequestContent) SetLink4(v string) {
	o.Link4 = &v
}

// GetLink5 returns the Link5 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink5() string {
	if o == nil || IsNil(o.Link5) {
		var ret string
		return ret
	}
	return *o.Link5
}

// GetLink5Ok returns a tuple with the Link5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink5Ok() (*string, bool) {
	if o == nil || IsNil(o.Link5) {
		return nil, false
	}
	return o.Link5, true
}

// HasLink5 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink5() bool {
	if o != nil && !IsNil(o.Link5) {
		return true
	}

	return false
}

// SetLink5 gets a reference to the given string and assigns it to the Link5 field.
func (o *CreateClusterConfigRequestContent) SetLink5(v string) {
	o.Link5 = &v
}

// GetLink6 returns the Link6 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink6() string {
	if o == nil || IsNil(o.Link6) {
		var ret string
		return ret
	}
	return *o.Link6
}

// GetLink6Ok returns a tuple with the Link6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink6Ok() (*string, bool) {
	if o == nil || IsNil(o.Link6) {
		return nil, false
	}
	return o.Link6, true
}

// HasLink6 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink6() bool {
	if o != nil && !IsNil(o.Link6) {
		return true
	}

	return false
}

// SetLink6 gets a reference to the given string and assigns it to the Link6 field.
func (o *CreateClusterConfigRequestContent) SetLink6(v string) {
	o.Link6 = &v
}

// GetLink7 returns the Link7 field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetLink7() string {
	if o == nil || IsNil(o.Link7) {
		var ret string
		return ret
	}
	return *o.Link7
}

// GetLink7Ok returns a tuple with the Link7 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetLink7Ok() (*string, bool) {
	if o == nil || IsNil(o.Link7) {
		return nil, false
	}
	return o.Link7, true
}

// HasLink7 returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasLink7() bool {
	if o != nil && !IsNil(o.Link7) {
		return true
	}

	return false
}

// SetLink7 gets a reference to the given string and assigns it to the Link7 field.
func (o *CreateClusterConfigRequestContent) SetLink7(v string) {
	o.Link7 = &v
}

// GetNodeid returns the Nodeid field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetNodeid() float32 {
	if o == nil || IsNil(o.Nodeid) {
		var ret float32
		return ret
	}
	return *o.Nodeid
}

// GetNodeidOk returns a tuple with the Nodeid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetNodeidOk() (*float32, bool) {
	if o == nil || IsNil(o.Nodeid) {
		return nil, false
	}
	return o.Nodeid, true
}

// HasNodeid returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasNodeid() bool {
	if o != nil && !IsNil(o.Nodeid) {
		return true
	}

	return false
}

// SetNodeid gets a reference to the given float32 and assigns it to the Nodeid field.
func (o *CreateClusterConfigRequestContent) SetNodeid(v float32) {
	o.Nodeid = &v
}

// GetVotes returns the Votes field value if set, zero value otherwise.
func (o *CreateClusterConfigRequestContent) GetVotes() float32 {
	if o == nil || IsNil(o.Votes) {
		var ret float32
		return ret
	}
	return *o.Votes
}

// GetVotesOk returns a tuple with the Votes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterConfigRequestContent) GetVotesOk() (*float32, bool) {
	if o == nil || IsNil(o.Votes) {
		return nil, false
	}
	return o.Votes, true
}

// HasVotes returns a boolean if a field has been set.
func (o *CreateClusterConfigRequestContent) HasVotes() bool {
	if o != nil && !IsNil(o.Votes) {
		return true
	}

	return false
}

// SetVotes gets a reference to the given float32 and assigns it to the Votes field.
func (o *CreateClusterConfigRequestContent) SetVotes(v float32) {
	o.Votes = &v
}

func (o CreateClusterConfigRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClusterConfigRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clustername"] = o.Clustername
	if !IsNil(o.Link0) {
		toSerialize["link0"] = o.Link0
	}
	if !IsNil(o.Link1) {
		toSerialize["link1"] = o.Link1
	}
	if !IsNil(o.Link2) {
		toSerialize["link2"] = o.Link2
	}
	if !IsNil(o.Link3) {
		toSerialize["link3"] = o.Link3
	}
	if !IsNil(o.Link4) {
		toSerialize["link4"] = o.Link4
	}
	if !IsNil(o.Link5) {
		toSerialize["link5"] = o.Link5
	}
	if !IsNil(o.Link6) {
		toSerialize["link6"] = o.Link6
	}
	if !IsNil(o.Link7) {
		toSerialize["link7"] = o.Link7
	}
	if !IsNil(o.Nodeid) {
		toSerialize["nodeid"] = o.Nodeid
	}
	if !IsNil(o.Votes) {
		toSerialize["votes"] = o.Votes
	}
	return toSerialize, nil
}

type NullableCreateClusterConfigRequestContent struct {
	value *CreateClusterConfigRequestContent
	isSet bool
}

func (v NullableCreateClusterConfigRequestContent) Get() *CreateClusterConfigRequestContent {
	return v.value
}

func (v *NullableCreateClusterConfigRequestContent) Set(val *CreateClusterConfigRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterConfigRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterConfigRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterConfigRequestContent(val *CreateClusterConfigRequestContent) *NullableCreateClusterConfigRequestContent {
	return &NullableCreateClusterConfigRequestContent{value: val, isSet: true}
}

func (v NullableCreateClusterConfigRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterConfigRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


