/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the NodeDnsSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeDnsSummary{}

// NodeDnsSummary struct for NodeDnsSummary
type NodeDnsSummary struct {
	Dns1 *string `json:"dns1,omitempty"`
	Dns2 *string `json:"dns2,omitempty"`
	Dns3 *string `json:"dns3,omitempty"`
	Search *string `json:"search,omitempty"`
}

// NewNodeDnsSummary instantiates a new NodeDnsSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeDnsSummary() *NodeDnsSummary {
	this := NodeDnsSummary{}
	return &this
}

// NewNodeDnsSummaryWithDefaults instantiates a new NodeDnsSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeDnsSummaryWithDefaults() *NodeDnsSummary {
	this := NodeDnsSummary{}
	return &this
}

// GetDns1 returns the Dns1 field value if set, zero value otherwise.
func (o *NodeDnsSummary) GetDns1() string {
	if o == nil || IsNil(o.Dns1) {
		var ret string
		return ret
	}
	return *o.Dns1
}

// GetDns1Ok returns a tuple with the Dns1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeDnsSummary) GetDns1Ok() (*string, bool) {
	if o == nil || IsNil(o.Dns1) {
		return nil, false
	}
	return o.Dns1, true
}

// HasDns1 returns a boolean if a field has been set.
func (o *NodeDnsSummary) HasDns1() bool {
	if o != nil && !IsNil(o.Dns1) {
		return true
	}

	return false
}

// SetDns1 gets a reference to the given string and assigns it to the Dns1 field.
func (o *NodeDnsSummary) SetDns1(v string) {
	o.Dns1 = &v
}

// GetDns2 returns the Dns2 field value if set, zero value otherwise.
func (o *NodeDnsSummary) GetDns2() string {
	if o == nil || IsNil(o.Dns2) {
		var ret string
		return ret
	}
	return *o.Dns2
}

// GetDns2Ok returns a tuple with the Dns2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeDnsSummary) GetDns2Ok() (*string, bool) {
	if o == nil || IsNil(o.Dns2) {
		return nil, false
	}
	return o.Dns2, true
}

// HasDns2 returns a boolean if a field has been set.
func (o *NodeDnsSummary) HasDns2() bool {
	if o != nil && !IsNil(o.Dns2) {
		return true
	}

	return false
}

// SetDns2 gets a reference to the given string and assigns it to the Dns2 field.
func (o *NodeDnsSummary) SetDns2(v string) {
	o.Dns2 = &v
}

// GetDns3 returns the Dns3 field value if set, zero value otherwise.
func (o *NodeDnsSummary) GetDns3() string {
	if o == nil || IsNil(o.Dns3) {
		var ret string
		return ret
	}
	return *o.Dns3
}

// GetDns3Ok returns a tuple with the Dns3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeDnsSummary) GetDns3Ok() (*string, bool) {
	if o == nil || IsNil(o.Dns3) {
		return nil, false
	}
	return o.Dns3, true
}

// HasDns3 returns a boolean if a field has been set.
func (o *NodeDnsSummary) HasDns3() bool {
	if o != nil && !IsNil(o.Dns3) {
		return true
	}

	return false
}

// SetDns3 gets a reference to the given string and assigns it to the Dns3 field.
func (o *NodeDnsSummary) SetDns3(v string) {
	o.Dns3 = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *NodeDnsSummary) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeDnsSummary) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *NodeDnsSummary) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *NodeDnsSummary) SetSearch(v string) {
	o.Search = &v
}

func (o NodeDnsSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeDnsSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dns1) {
		toSerialize["dns1"] = o.Dns1
	}
	if !IsNil(o.Dns2) {
		toSerialize["dns2"] = o.Dns2
	}
	if !IsNil(o.Dns3) {
		toSerialize["dns3"] = o.Dns3
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	return toSerialize, nil
}

type NullableNodeDnsSummary struct {
	value *NodeDnsSummary
	isSet bool
}

func (v NullableNodeDnsSummary) Get() *NodeDnsSummary {
	return v.value
}

func (v *NullableNodeDnsSummary) Set(val *NodeDnsSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeDnsSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeDnsSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeDnsSummary(val *NodeDnsSummary) *NullableNodeDnsSummary {
	return &NullableNodeDnsSummary{value: val, isSet: true}
}

func (v NullableNodeDnsSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeDnsSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


