/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the GetPackageChangelogResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPackageChangelogResponseContent{}

// GetPackageChangelogResponseContent struct for GetPackageChangelogResponseContent
type GetPackageChangelogResponseContent struct {
	Data string `json:"data"`
}

// NewGetPackageChangelogResponseContent instantiates a new GetPackageChangelogResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPackageChangelogResponseContent(data string) *GetPackageChangelogResponseContent {
	this := GetPackageChangelogResponseContent{}
	this.Data = data
	return &this
}

// NewGetPackageChangelogResponseContentWithDefaults instantiates a new GetPackageChangelogResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPackageChangelogResponseContentWithDefaults() *GetPackageChangelogResponseContent {
	this := GetPackageChangelogResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *GetPackageChangelogResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPackageChangelogResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPackageChangelogResponseContent) SetData(v string) {
	o.Data = v
}

func (o GetPackageChangelogResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPackageChangelogResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGetPackageChangelogResponseContent struct {
	value *GetPackageChangelogResponseContent
	isSet bool
}

func (v NullableGetPackageChangelogResponseContent) Get() *GetPackageChangelogResponseContent {
	return v.value
}

func (v *NullableGetPackageChangelogResponseContent) Set(val *GetPackageChangelogResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPackageChangelogResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPackageChangelogResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPackageChangelogResponseContent(val *GetPackageChangelogResponseContent) *NullableGetPackageChangelogResponseContent {
	return &NullableGetPackageChangelogResponseContent{value: val, isSet: true}
}

func (v NullableGetPackageChangelogResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPackageChangelogResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


