/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the CreateLVMRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLVMRequestContent{}

// CreateLVMRequestContent struct for CreateLVMRequestContent
type CreateLVMRequestContent struct {
	// The device to create the lvm on.
	Device string `json:"device"`
	// The storage identifier.
	Name string `json:"name"`
	// Configure storage using the lvm. Takes a boolean integer value (0 false, 1 true).
	AddStorage *float32 `json:"add_storage,omitempty"`
}

// NewCreateLVMRequestContent instantiates a new CreateLVMRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLVMRequestContent(device string, name string) *CreateLVMRequestContent {
	this := CreateLVMRequestContent{}
	this.Device = device
	this.Name = name
	return &this
}

// NewCreateLVMRequestContentWithDefaults instantiates a new CreateLVMRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLVMRequestContentWithDefaults() *CreateLVMRequestContent {
	this := CreateLVMRequestContent{}
	return &this
}

// GetDevice returns the Device field value
func (o *CreateLVMRequestContent) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *CreateLVMRequestContent) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *CreateLVMRequestContent) SetDevice(v string) {
	o.Device = v
}

// GetName returns the Name field value
func (o *CreateLVMRequestContent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateLVMRequestContent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateLVMRequestContent) SetName(v string) {
	o.Name = v
}

// GetAddStorage returns the AddStorage field value if set, zero value otherwise.
func (o *CreateLVMRequestContent) GetAddStorage() float32 {
	if o == nil || IsNil(o.AddStorage) {
		var ret float32
		return ret
	}
	return *o.AddStorage
}

// GetAddStorageOk returns a tuple with the AddStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLVMRequestContent) GetAddStorageOk() (*float32, bool) {
	if o == nil || IsNil(o.AddStorage) {
		return nil, false
	}
	return o.AddStorage, true
}

// HasAddStorage returns a boolean if a field has been set.
func (o *CreateLVMRequestContent) HasAddStorage() bool {
	if o != nil && !IsNil(o.AddStorage) {
		return true
	}

	return false
}

// SetAddStorage gets a reference to the given float32 and assigns it to the AddStorage field.
func (o *CreateLVMRequestContent) SetAddStorage(v float32) {
	o.AddStorage = &v
}

func (o CreateLVMRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLVMRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device"] = o.Device
	toSerialize["name"] = o.Name
	if !IsNil(o.AddStorage) {
		toSerialize["add_storage"] = o.AddStorage
	}
	return toSerialize, nil
}

type NullableCreateLVMRequestContent struct {
	value *CreateLVMRequestContent
	isSet bool
}

func (v NullableCreateLVMRequestContent) Get() *CreateLVMRequestContent {
	return v.value
}

func (v *NullableCreateLVMRequestContent) Set(val *CreateLVMRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLVMRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLVMRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLVMRequestContent(val *CreateLVMRequestContent) *NullableCreateLVMRequestContent {
	return &NullableCreateLVMRequestContent{value: val, isSet: true}
}

func (v NullableCreateLVMRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLVMRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


