/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the RebootVirtualMachineResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RebootVirtualMachineResponseContent{}

// RebootVirtualMachineResponseContent struct for RebootVirtualMachineResponseContent
type RebootVirtualMachineResponseContent struct {
	Data string `json:"data"`
}

// NewRebootVirtualMachineResponseContent instantiates a new RebootVirtualMachineResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRebootVirtualMachineResponseContent(data string) *RebootVirtualMachineResponseContent {
	this := RebootVirtualMachineResponseContent{}
	this.Data = data
	return &this
}

// NewRebootVirtualMachineResponseContentWithDefaults instantiates a new RebootVirtualMachineResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRebootVirtualMachineResponseContentWithDefaults() *RebootVirtualMachineResponseContent {
	this := RebootVirtualMachineResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *RebootVirtualMachineResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RebootVirtualMachineResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RebootVirtualMachineResponseContent) SetData(v string) {
	o.Data = v
}

func (o RebootVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RebootVirtualMachineResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableRebootVirtualMachineResponseContent struct {
	value *RebootVirtualMachineResponseContent
	isSet bool
}

func (v NullableRebootVirtualMachineResponseContent) Get() *RebootVirtualMachineResponseContent {
	return v.value
}

func (v *NullableRebootVirtualMachineResponseContent) Set(val *RebootVirtualMachineResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRebootVirtualMachineResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRebootVirtualMachineResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRebootVirtualMachineResponseContent(val *RebootVirtualMachineResponseContent) *NullableRebootVirtualMachineResponseContent {
	return &NullableRebootVirtualMachineResponseContent{value: val, isSet: true}
}

func (v NullableRebootVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRebootVirtualMachineResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


