/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the ListRolesResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRolesResponseContent{}

// ListRolesResponseContent struct for ListRolesResponseContent
type ListRolesResponseContent struct {
	Data []RoleSummary `json:"data"`
}

// NewListRolesResponseContent instantiates a new ListRolesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRolesResponseContent(data []RoleSummary) *ListRolesResponseContent {
	this := ListRolesResponseContent{}
	this.Data = data
	return &this
}

// NewListRolesResponseContentWithDefaults instantiates a new ListRolesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRolesResponseContentWithDefaults() *ListRolesResponseContent {
	this := ListRolesResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListRolesResponseContent) GetData() []RoleSummary {
	if o == nil {
		var ret []RoleSummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListRolesResponseContent) GetDataOk() ([]RoleSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListRolesResponseContent) SetData(v []RoleSummary) {
	o.Data = v
}

func (o ListRolesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRolesResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListRolesResponseContent struct {
	value *ListRolesResponseContent
	isSet bool
}

func (v NullableListRolesResponseContent) Get() *ListRolesResponseContent {
	return v.value
}

func (v *NullableListRolesResponseContent) Set(val *ListRolesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListRolesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListRolesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRolesResponseContent(val *ListRolesResponseContent) *NullableListRolesResponseContent {
	return &NullableListRolesResponseContent{value: val, isSet: true}
}

func (v NullableListRolesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRolesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


