/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the GroupSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupSummary{}

// GroupSummary struct for GroupSummary
type GroupSummary struct {
	Groupid string `json:"groupid"`
	Users *string `json:"users,omitempty"`
	Comment *string `json:"comment,omitempty"`
}

// NewGroupSummary instantiates a new GroupSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupSummary(groupid string) *GroupSummary {
	this := GroupSummary{}
	this.Groupid = groupid
	return &this
}

// NewGroupSummaryWithDefaults instantiates a new GroupSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupSummaryWithDefaults() *GroupSummary {
	this := GroupSummary{}
	return &this
}

// GetGroupid returns the Groupid field value
func (o *GroupSummary) GetGroupid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Groupid
}

// GetGroupidOk returns a tuple with the Groupid field value
// and a boolean to check if the value has been set.
func (o *GroupSummary) GetGroupidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Groupid, true
}

// SetGroupid sets field value
func (o *GroupSummary) SetGroupid(v string) {
	o.Groupid = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *GroupSummary) GetUsers() string {
	if o == nil || isNil(o.Users) {
		var ret string
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupSummary) GetUsersOk() (*string, bool) {
	if o == nil || isNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *GroupSummary) HasUsers() bool {
	if o != nil && !isNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given string and assigns it to the Users field.
func (o *GroupSummary) SetUsers(v string) {
	o.Users = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *GroupSummary) GetComment() string {
	if o == nil || isNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupSummary) GetCommentOk() (*string, bool) {
	if o == nil || isNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *GroupSummary) HasComment() bool {
	if o != nil && !isNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *GroupSummary) SetComment(v string) {
	o.Comment = &v
}

func (o GroupSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groupid"] = o.Groupid
	if !isNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !isNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

type NullableGroupSummary struct {
	value *GroupSummary
	isSet bool
}

func (v NullableGroupSummary) Get() *GroupSummary {
	return v.value
}

func (v *NullableGroupSummary) Set(val *GroupSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupSummary(val *GroupSummary) *NullableGroupSummary {
	return &NullableGroupSummary{value: val, isSet: true}
}

func (v NullableGroupSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


