/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the DeleteCephMonitorResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteCephMonitorResponseContent{}

// DeleteCephMonitorResponseContent struct for DeleteCephMonitorResponseContent
type DeleteCephMonitorResponseContent struct {
	Data string `json:"data"`
}

// NewDeleteCephMonitorResponseContent instantiates a new DeleteCephMonitorResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteCephMonitorResponseContent(data string) *DeleteCephMonitorResponseContent {
	this := DeleteCephMonitorResponseContent{}
	this.Data = data
	return &this
}

// NewDeleteCephMonitorResponseContentWithDefaults instantiates a new DeleteCephMonitorResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteCephMonitorResponseContentWithDefaults() *DeleteCephMonitorResponseContent {
	this := DeleteCephMonitorResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteCephMonitorResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteCephMonitorResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteCephMonitorResponseContent) SetData(v string) {
	o.Data = v
}

func (o DeleteCephMonitorResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteCephMonitorResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableDeleteCephMonitorResponseContent struct {
	value *DeleteCephMonitorResponseContent
	isSet bool
}

func (v NullableDeleteCephMonitorResponseContent) Get() *DeleteCephMonitorResponseContent {
	return v.value
}

func (v *NullableDeleteCephMonitorResponseContent) Set(val *DeleteCephMonitorResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCephMonitorResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCephMonitorResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCephMonitorResponseContent(val *DeleteCephMonitorResponseContent) *NullableDeleteCephMonitorResponseContent {
	return &NullableDeleteCephMonitorResponseContent{value: val, isSet: true}
}

func (v NullableDeleteCephMonitorResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCephMonitorResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


