/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// CreateVirtualMachineResponseContent struct for CreateVirtualMachineResponseContent
type CreateVirtualMachineResponseContent struct {
	Data string `json:"data"`
}

// NewCreateVirtualMachineResponseContent instantiates a new CreateVirtualMachineResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVirtualMachineResponseContent(data string) *CreateVirtualMachineResponseContent {
	this := CreateVirtualMachineResponseContent{}
	this.Data = data
	return &this
}

// NewCreateVirtualMachineResponseContentWithDefaults instantiates a new CreateVirtualMachineResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVirtualMachineResponseContentWithDefaults() *CreateVirtualMachineResponseContent {
	this := CreateVirtualMachineResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *CreateVirtualMachineResponseContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateVirtualMachineResponseContent) GetDataOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateVirtualMachineResponseContent) SetData(v string) {
	o.Data = v
}

func (o CreateVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateVirtualMachineResponseContent struct {
	value *CreateVirtualMachineResponseContent
	isSet bool
}

func (v NullableCreateVirtualMachineResponseContent) Get() *CreateVirtualMachineResponseContent {
	return v.value
}

func (v *NullableCreateVirtualMachineResponseContent) Set(val *CreateVirtualMachineResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVirtualMachineResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVirtualMachineResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVirtualMachineResponseContent(val *CreateVirtualMachineResponseContent) *NullableCreateVirtualMachineResponseContent {
	return &NullableCreateVirtualMachineResponseContent{value: val, isSet: true}
}

func (v NullableCreateVirtualMachineResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVirtualMachineResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


