/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the VirtualNetworkInterfaceSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VirtualNetworkInterfaceSummary{}

// VirtualNetworkInterfaceSummary struct for VirtualNetworkInterfaceSummary
type VirtualNetworkInterfaceSummary struct {
	Name *string `json:"name,omitempty"`
	Statistics *NetworkInterfaceStatisticsSummary `json:"statistics,omitempty"`
	IpAddresses []NetworkInterfaceIpAddressSummary `json:"ip-addresses,omitempty"`
	HardwareAddress *string `json:"hardware-address,omitempty"`
}

// NewVirtualNetworkInterfaceSummary instantiates a new VirtualNetworkInterfaceSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualNetworkInterfaceSummary() *VirtualNetworkInterfaceSummary {
	this := VirtualNetworkInterfaceSummary{}
	return &this
}

// NewVirtualNetworkInterfaceSummaryWithDefaults instantiates a new VirtualNetworkInterfaceSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualNetworkInterfaceSummaryWithDefaults() *VirtualNetworkInterfaceSummary {
	this := VirtualNetworkInterfaceSummary{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VirtualNetworkInterfaceSummary) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualNetworkInterfaceSummary) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VirtualNetworkInterfaceSummary) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VirtualNetworkInterfaceSummary) SetName(v string) {
	o.Name = &v
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
func (o *VirtualNetworkInterfaceSummary) GetStatistics() NetworkInterfaceStatisticsSummary {
	if o == nil || isNil(o.Statistics) {
		var ret NetworkInterfaceStatisticsSummary
		return ret
	}
	return *o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualNetworkInterfaceSummary) GetStatisticsOk() (*NetworkInterfaceStatisticsSummary, bool) {
	if o == nil || isNil(o.Statistics) {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *VirtualNetworkInterfaceSummary) HasStatistics() bool {
	if o != nil && !isNil(o.Statistics) {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given NetworkInterfaceStatisticsSummary and assigns it to the Statistics field.
func (o *VirtualNetworkInterfaceSummary) SetStatistics(v NetworkInterfaceStatisticsSummary) {
	o.Statistics = &v
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *VirtualNetworkInterfaceSummary) GetIpAddresses() []NetworkInterfaceIpAddressSummary {
	if o == nil || isNil(o.IpAddresses) {
		var ret []NetworkInterfaceIpAddressSummary
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualNetworkInterfaceSummary) GetIpAddressesOk() ([]NetworkInterfaceIpAddressSummary, bool) {
	if o == nil || isNil(o.IpAddresses) {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *VirtualNetworkInterfaceSummary) HasIpAddresses() bool {
	if o != nil && !isNil(o.IpAddresses) {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []NetworkInterfaceIpAddressSummary and assigns it to the IpAddresses field.
func (o *VirtualNetworkInterfaceSummary) SetIpAddresses(v []NetworkInterfaceIpAddressSummary) {
	o.IpAddresses = v
}

// GetHardwareAddress returns the HardwareAddress field value if set, zero value otherwise.
func (o *VirtualNetworkInterfaceSummary) GetHardwareAddress() string {
	if o == nil || isNil(o.HardwareAddress) {
		var ret string
		return ret
	}
	return *o.HardwareAddress
}

// GetHardwareAddressOk returns a tuple with the HardwareAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualNetworkInterfaceSummary) GetHardwareAddressOk() (*string, bool) {
	if o == nil || isNil(o.HardwareAddress) {
		return nil, false
	}
	return o.HardwareAddress, true
}

// HasHardwareAddress returns a boolean if a field has been set.
func (o *VirtualNetworkInterfaceSummary) HasHardwareAddress() bool {
	if o != nil && !isNil(o.HardwareAddress) {
		return true
	}

	return false
}

// SetHardwareAddress gets a reference to the given string and assigns it to the HardwareAddress field.
func (o *VirtualNetworkInterfaceSummary) SetHardwareAddress(v string) {
	o.HardwareAddress = &v
}

func (o VirtualNetworkInterfaceSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VirtualNetworkInterfaceSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Statistics) {
		toSerialize["statistics"] = o.Statistics
	}
	if !isNil(o.IpAddresses) {
		toSerialize["ip-addresses"] = o.IpAddresses
	}
	if !isNil(o.HardwareAddress) {
		toSerialize["hardware-address"] = o.HardwareAddress
	}
	return toSerialize, nil
}

type NullableVirtualNetworkInterfaceSummary struct {
	value *VirtualNetworkInterfaceSummary
	isSet bool
}

func (v NullableVirtualNetworkInterfaceSummary) Get() *VirtualNetworkInterfaceSummary {
	return v.value
}

func (v *NullableVirtualNetworkInterfaceSummary) Set(val *VirtualNetworkInterfaceSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualNetworkInterfaceSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualNetworkInterfaceSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualNetworkInterfaceSummary(val *VirtualNetworkInterfaceSummary) *NullableVirtualNetworkInterfaceSummary {
	return &NullableVirtualNetworkInterfaceSummary{value: val, isSet: true}
}

func (v NullableVirtualNetworkInterfaceSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualNetworkInterfaceSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


