/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the NoGuestAgentErrorResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoGuestAgentErrorResponseContent{}

// NoGuestAgentErrorResponseContent struct for NoGuestAgentErrorResponseContent
type NoGuestAgentErrorResponseContent struct {
	Message string `json:"message"`
}

// NewNoGuestAgentErrorResponseContent instantiates a new NoGuestAgentErrorResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoGuestAgentErrorResponseContent(message string) *NoGuestAgentErrorResponseContent {
	this := NoGuestAgentErrorResponseContent{}
	this.Message = message
	return &this
}

// NewNoGuestAgentErrorResponseContentWithDefaults instantiates a new NoGuestAgentErrorResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoGuestAgentErrorResponseContentWithDefaults() *NoGuestAgentErrorResponseContent {
	this := NoGuestAgentErrorResponseContent{}
	return &this
}

// GetMessage returns the Message field value
func (o *NoGuestAgentErrorResponseContent) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *NoGuestAgentErrorResponseContent) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *NoGuestAgentErrorResponseContent) SetMessage(v string) {
	o.Message = v
}

func (o NoGuestAgentErrorResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoGuestAgentErrorResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

type NullableNoGuestAgentErrorResponseContent struct {
	value *NoGuestAgentErrorResponseContent
	isSet bool
}

func (v NullableNoGuestAgentErrorResponseContent) Get() *NoGuestAgentErrorResponseContent {
	return v.value
}

func (v *NullableNoGuestAgentErrorResponseContent) Set(val *NoGuestAgentErrorResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableNoGuestAgentErrorResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableNoGuestAgentErrorResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoGuestAgentErrorResponseContent(val *NoGuestAgentErrorResponseContent) *NullableNoGuestAgentErrorResponseContent {
	return &NullableNoGuestAgentErrorResponseContent{value: val, isSet: true}
}

func (v NullableNoGuestAgentErrorResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoGuestAgentErrorResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


