/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// ListPoolsResponseContent struct for ListPoolsResponseContent
type ListPoolsResponseContent struct {
	Data []PoolInfo `json:"data"`
}

// NewListPoolsResponseContent instantiates a new ListPoolsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPoolsResponseContent(data []PoolInfo) *ListPoolsResponseContent {
	this := ListPoolsResponseContent{}
	this.Data = data
	return &this
}

// NewListPoolsResponseContentWithDefaults instantiates a new ListPoolsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPoolsResponseContentWithDefaults() *ListPoolsResponseContent {
	this := ListPoolsResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListPoolsResponseContent) GetData() []PoolInfo {
	if o == nil {
		var ret []PoolInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListPoolsResponseContent) GetDataOk() ([]PoolInfo, bool) {
	if o == nil {
    return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListPoolsResponseContent) SetData(v []PoolInfo) {
	o.Data = v
}

func (o ListPoolsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableListPoolsResponseContent struct {
	value *ListPoolsResponseContent
	isSet bool
}

func (v NullableListPoolsResponseContent) Get() *ListPoolsResponseContent {
	return v.value
}

func (v *NullableListPoolsResponseContent) Set(val *ListPoolsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListPoolsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListPoolsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPoolsResponseContent(val *ListPoolsResponseContent) *NullableListPoolsResponseContent {
	return &NullableListPoolsResponseContent{value: val, isSet: true}
}

func (v NullableListPoolsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPoolsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


