/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the GetVirtualMachineTimeZoneResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVirtualMachineTimeZoneResponseContent{}

// GetVirtualMachineTimeZoneResponseContent struct for GetVirtualMachineTimeZoneResponseContent
type GetVirtualMachineTimeZoneResponseContent struct {
	Data GetTimeZoneResult `json:"data"`
}

// NewGetVirtualMachineTimeZoneResponseContent instantiates a new GetVirtualMachineTimeZoneResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVirtualMachineTimeZoneResponseContent(data GetTimeZoneResult) *GetVirtualMachineTimeZoneResponseContent {
	this := GetVirtualMachineTimeZoneResponseContent{}
	this.Data = data
	return &this
}

// NewGetVirtualMachineTimeZoneResponseContentWithDefaults instantiates a new GetVirtualMachineTimeZoneResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVirtualMachineTimeZoneResponseContentWithDefaults() *GetVirtualMachineTimeZoneResponseContent {
	this := GetVirtualMachineTimeZoneResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *GetVirtualMachineTimeZoneResponseContent) GetData() GetTimeZoneResult {
	if o == nil {
		var ret GetTimeZoneResult
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetVirtualMachineTimeZoneResponseContent) GetDataOk() (*GetTimeZoneResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetVirtualMachineTimeZoneResponseContent) SetData(v GetTimeZoneResult) {
	o.Data = v
}

func (o GetVirtualMachineTimeZoneResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVirtualMachineTimeZoneResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGetVirtualMachineTimeZoneResponseContent struct {
	value *GetVirtualMachineTimeZoneResponseContent
	isSet bool
}

func (v NullableGetVirtualMachineTimeZoneResponseContent) Get() *GetVirtualMachineTimeZoneResponseContent {
	return v.value
}

func (v *NullableGetVirtualMachineTimeZoneResponseContent) Set(val *GetVirtualMachineTimeZoneResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVirtualMachineTimeZoneResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVirtualMachineTimeZoneResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVirtualMachineTimeZoneResponseContent(val *GetVirtualMachineTimeZoneResponseContent) *NullableGetVirtualMachineTimeZoneResponseContent {
	return &NullableGetVirtualMachineTimeZoneResponseContent{value: val, isSet: true}
}

func (v NullableGetVirtualMachineTimeZoneResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVirtualMachineTimeZoneResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


