/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the CreateStorageRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStorageRequestContent{}

// CreateStorageRequestContent struct for CreateStorageRequestContent
type CreateStorageRequestContent struct {
	Storage string `json:"storage"`
	Type StorageType `json:"type"`
	Authsupported *string `json:"authsupported,omitempty"`
	// The base volume to use. 
	Base *string `json:"base,omitempty"`
	Blocksize *string `json:"blocksize,omitempty"`
	Bwlimit *string `json:"bwlimit,omitempty"`
	ComstarHg *string `json:"comstar_hg,omitempty"`
	ComstarTg *string `json:"comstar_tg,omitempty"`
	// Allowed content types.
	Content *string `json:"content,omitempty"`
	// Data pool, only for erasure coding
	DataPool *string `json:"data-pool,omitempty"`
	// Disable the storage
	Disable *bool `json:"disable,omitempty"`
	// CIFS domain
	Domain *string `json:"domain,omitempty"`
	// Encryption key for storage. Use 'autogen' to generate one automatically without passphrase.
	EncryptionKey *string `json:"encryption-key,omitempty"`
	// NFS export path
	Export *string `json:"export,omitempty"`
	// Certificate SHA256 fingerprint
	Fingerprint *string `json:"fingerprint,omitempty"`
	// Default image format
	Format *string `json:"format,omitempty"`
	// The ceph filesystem name
	FsName *string `json:"fs-name,omitempty"`
	// Mount CephFS through FUSE
	Fuse *bool `json:"fuse,omitempty"`
	// Assume the given path is an externally managed mountpoint. This is a string boolean, using 'yes' or 'no'
	IsMountpoint *string `json:"is_mountpoint,omitempty"`
	// iSCSI provider
	Iscsiprovider *string `json:"iscsiprovider,omitempty"`
	// Client keyring contents
	Keyring *string `json:"keyring,omitempty"`
	// Always access rbd through krbd kernel module
	Krbd *bool `json:"krbd,omitempty"`
	// Target portal group for Linux LIO targets
	LioTpg *string `json:"lio_tpg,omitempty"`
	// Base64 encoded, PEM formatted public RSA key
	MasterPubkey *string `json:"master-pubkey,omitempty"`
	// Mac number of protected backups. Defaults to unlimited
	MaxProtectedBackups *float32 `json:"max-protected-backups,omitempty"`
	// Create the directory if doesnt exist. Defaults to true.
	Mkdir *bool `json:"mkdir,omitempty"`
	// IP addresses of monitors.
	Monhost *string `json:"monhost,omitempty"`
	// The mount point
	Mountpoint *string `json:"mountpoint,omitempty"`
	// The namespace
	Namespace *string `json:"namespace,omitempty"`
	// Set the NOCOW flag on files. This is a boolean integer, using 0 for false or 1 for true.
	Nocow *float32 `json:"nocow,omitempty"`
	// Comma seperated list of node names
	Nodes *string `json:"nodes,omitempty"`
	// Disable write caching on the target.
	Nowritecache *bool `json:"nowritecache,omitempty"`
	// NFS mount options.
	Options *string `json:"options,omitempty"`
	// Password for accessing the datastore
	Password *string `json:"password,omitempty"`
	// The filesystem path
	Path *string `json:"path,omitempty"`
	// The pool name
	Pool *string `json:"pool,omitempty"`
	// For non default port
	Port *float32 `json:"port,omitempty"`
	// iSCSI portal (IP or DNS name with optional port).
	Portal *string `json:"portal,omitempty"`
	Preallocation *StoragePreallocation `json:"preallocation,omitempty"`
	// The retention options.
	PruneBackups *string `json:"prune-backups,omitempty"`
	// Zero out data when removing LVs
	Saferemove *bool `json:"saferemove,omitempty"`
	// Wipe throughput.
	SaferemoveThroughput *string `json:"saferemove-throughput,omitempty"`
	// Server IP or DNS name
	Server *string `json:"server,omitempty"`
	// Backup server IP or DNS name
	Server2 *string `json:"server2,omitempty"`
	// The CIFS share.
	Share *string `json:"share,omitempty"`
	// Indicates if the storage is shared.
	Shared *bool `json:"shared,omitempty"`
	Smbversion *StorageSMBVersion `json:"smbversion,omitempty"`
	// Use sparse volumes.
	Sparse *bool `json:"sparse,omitempty"`
	// The subdir to mount.
	Subdir *string `json:"subdir,omitempty"`
	// Only use logical volumes tagged with 'pve-vm-ID'.
	TaggedOnly *bool `json:"tagged_only,omitempty"`
	// LVM thin pool name.
	Thinpool *string `json:"thinpool,omitempty"`
	Transport *StorageTransport `json:"transport,omitempty"`
	// The username to use.
	Username *string `json:"username,omitempty"`
	// The volume group name.
	Vgname *string `json:"vgname,omitempty"`
	// The glusterfs volume.
	Volume *string `json:"volume,omitempty"`
}

// NewCreateStorageRequestContent instantiates a new CreateStorageRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStorageRequestContent(storage string, type_ StorageType) *CreateStorageRequestContent {
	this := CreateStorageRequestContent{}
	this.Storage = storage
	this.Type = type_
	return &this
}

// NewCreateStorageRequestContentWithDefaults instantiates a new CreateStorageRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStorageRequestContentWithDefaults() *CreateStorageRequestContent {
	this := CreateStorageRequestContent{}
	return &this
}

// GetStorage returns the Storage field value
func (o *CreateStorageRequestContent) GetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *CreateStorageRequestContent) SetStorage(v string) {
	o.Storage = v
}

// GetType returns the Type field value
func (o *CreateStorageRequestContent) GetType() StorageType {
	if o == nil {
		var ret StorageType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetTypeOk() (*StorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateStorageRequestContent) SetType(v StorageType) {
	o.Type = v
}

// GetAuthsupported returns the Authsupported field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetAuthsupported() string {
	if o == nil || IsNil(o.Authsupported) {
		var ret string
		return ret
	}
	return *o.Authsupported
}

// GetAuthsupportedOk returns a tuple with the Authsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetAuthsupportedOk() (*string, bool) {
	if o == nil || IsNil(o.Authsupported) {
		return nil, false
	}
	return o.Authsupported, true
}

// HasAuthsupported returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasAuthsupported() bool {
	if o != nil && !IsNil(o.Authsupported) {
		return true
	}

	return false
}

// SetAuthsupported gets a reference to the given string and assigns it to the Authsupported field.
func (o *CreateStorageRequestContent) SetAuthsupported(v string) {
	o.Authsupported = &v
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetBase() string {
	if o == nil || IsNil(o.Base) {
		var ret string
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetBaseOk() (*string, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given string and assigns it to the Base field.
func (o *CreateStorageRequestContent) SetBase(v string) {
	o.Base = &v
}

// GetBlocksize returns the Blocksize field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetBlocksize() string {
	if o == nil || IsNil(o.Blocksize) {
		var ret string
		return ret
	}
	return *o.Blocksize
}

// GetBlocksizeOk returns a tuple with the Blocksize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetBlocksizeOk() (*string, bool) {
	if o == nil || IsNil(o.Blocksize) {
		return nil, false
	}
	return o.Blocksize, true
}

// HasBlocksize returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasBlocksize() bool {
	if o != nil && !IsNil(o.Blocksize) {
		return true
	}

	return false
}

// SetBlocksize gets a reference to the given string and assigns it to the Blocksize field.
func (o *CreateStorageRequestContent) SetBlocksize(v string) {
	o.Blocksize = &v
}

// GetBwlimit returns the Bwlimit field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetBwlimit() string {
	if o == nil || IsNil(o.Bwlimit) {
		var ret string
		return ret
	}
	return *o.Bwlimit
}

// GetBwlimitOk returns a tuple with the Bwlimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetBwlimitOk() (*string, bool) {
	if o == nil || IsNil(o.Bwlimit) {
		return nil, false
	}
	return o.Bwlimit, true
}

// HasBwlimit returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasBwlimit() bool {
	if o != nil && !IsNil(o.Bwlimit) {
		return true
	}

	return false
}

// SetBwlimit gets a reference to the given string and assigns it to the Bwlimit field.
func (o *CreateStorageRequestContent) SetBwlimit(v string) {
	o.Bwlimit = &v
}

// GetComstarHg returns the ComstarHg field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetComstarHg() string {
	if o == nil || IsNil(o.ComstarHg) {
		var ret string
		return ret
	}
	return *o.ComstarHg
}

// GetComstarHgOk returns a tuple with the ComstarHg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetComstarHgOk() (*string, bool) {
	if o == nil || IsNil(o.ComstarHg) {
		return nil, false
	}
	return o.ComstarHg, true
}

// HasComstarHg returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasComstarHg() bool {
	if o != nil && !IsNil(o.ComstarHg) {
		return true
	}

	return false
}

// SetComstarHg gets a reference to the given string and assigns it to the ComstarHg field.
func (o *CreateStorageRequestContent) SetComstarHg(v string) {
	o.ComstarHg = &v
}

// GetComstarTg returns the ComstarTg field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetComstarTg() string {
	if o == nil || IsNil(o.ComstarTg) {
		var ret string
		return ret
	}
	return *o.ComstarTg
}

// GetComstarTgOk returns a tuple with the ComstarTg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetComstarTgOk() (*string, bool) {
	if o == nil || IsNil(o.ComstarTg) {
		return nil, false
	}
	return o.ComstarTg, true
}

// HasComstarTg returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasComstarTg() bool {
	if o != nil && !IsNil(o.ComstarTg) {
		return true
	}

	return false
}

// SetComstarTg gets a reference to the given string and assigns it to the ComstarTg field.
func (o *CreateStorageRequestContent) SetComstarTg(v string) {
	o.ComstarTg = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *CreateStorageRequestContent) SetContent(v string) {
	o.Content = &v
}

// GetDataPool returns the DataPool field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetDataPool() string {
	if o == nil || IsNil(o.DataPool) {
		var ret string
		return ret
	}
	return *o.DataPool
}

// GetDataPoolOk returns a tuple with the DataPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetDataPoolOk() (*string, bool) {
	if o == nil || IsNil(o.DataPool) {
		return nil, false
	}
	return o.DataPool, true
}

// HasDataPool returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasDataPool() bool {
	if o != nil && !IsNil(o.DataPool) {
		return true
	}

	return false
}

// SetDataPool gets a reference to the given string and assigns it to the DataPool field.
func (o *CreateStorageRequestContent) SetDataPool(v string) {
	o.DataPool = &v
}

// GetDisable returns the Disable field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetDisable() bool {
	if o == nil || IsNil(o.Disable) {
		var ret bool
		return ret
	}
	return *o.Disable
}

// GetDisableOk returns a tuple with the Disable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetDisableOk() (*bool, bool) {
	if o == nil || IsNil(o.Disable) {
		return nil, false
	}
	return o.Disable, true
}

// HasDisable returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasDisable() bool {
	if o != nil && !IsNil(o.Disable) {
		return true
	}

	return false
}

// SetDisable gets a reference to the given bool and assigns it to the Disable field.
func (o *CreateStorageRequestContent) SetDisable(v bool) {
	o.Disable = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CreateStorageRequestContent) SetDomain(v string) {
	o.Domain = &v
}

// GetEncryptionKey returns the EncryptionKey field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetEncryptionKey() string {
	if o == nil || IsNil(o.EncryptionKey) {
		var ret string
		return ret
	}
	return *o.EncryptionKey
}

// GetEncryptionKeyOk returns a tuple with the EncryptionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetEncryptionKeyOk() (*string, bool) {
	if o == nil || IsNil(o.EncryptionKey) {
		return nil, false
	}
	return o.EncryptionKey, true
}

// HasEncryptionKey returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasEncryptionKey() bool {
	if o != nil && !IsNil(o.EncryptionKey) {
		return true
	}

	return false
}

// SetEncryptionKey gets a reference to the given string and assigns it to the EncryptionKey field.
func (o *CreateStorageRequestContent) SetEncryptionKey(v string) {
	o.EncryptionKey = &v
}

// GetExport returns the Export field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetExport() string {
	if o == nil || IsNil(o.Export) {
		var ret string
		return ret
	}
	return *o.Export
}

// GetExportOk returns a tuple with the Export field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetExportOk() (*string, bool) {
	if o == nil || IsNil(o.Export) {
		return nil, false
	}
	return o.Export, true
}

// HasExport returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasExport() bool {
	if o != nil && !IsNil(o.Export) {
		return true
	}

	return false
}

// SetExport gets a reference to the given string and assigns it to the Export field.
func (o *CreateStorageRequestContent) SetExport(v string) {
	o.Export = &v
}

// GetFingerprint returns the Fingerprint field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetFingerprint() string {
	if o == nil || IsNil(o.Fingerprint) {
		var ret string
		return ret
	}
	return *o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.Fingerprint) {
		return nil, false
	}
	return o.Fingerprint, true
}

// HasFingerprint returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasFingerprint() bool {
	if o != nil && !IsNil(o.Fingerprint) {
		return true
	}

	return false
}

// SetFingerprint gets a reference to the given string and assigns it to the Fingerprint field.
func (o *CreateStorageRequestContent) SetFingerprint(v string) {
	o.Fingerprint = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *CreateStorageRequestContent) SetFormat(v string) {
	o.Format = &v
}

// GetFsName returns the FsName field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetFsName() string {
	if o == nil || IsNil(o.FsName) {
		var ret string
		return ret
	}
	return *o.FsName
}

// GetFsNameOk returns a tuple with the FsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetFsNameOk() (*string, bool) {
	if o == nil || IsNil(o.FsName) {
		return nil, false
	}
	return o.FsName, true
}

// HasFsName returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasFsName() bool {
	if o != nil && !IsNil(o.FsName) {
		return true
	}

	return false
}

// SetFsName gets a reference to the given string and assigns it to the FsName field.
func (o *CreateStorageRequestContent) SetFsName(v string) {
	o.FsName = &v
}

// GetFuse returns the Fuse field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetFuse() bool {
	if o == nil || IsNil(o.Fuse) {
		var ret bool
		return ret
	}
	return *o.Fuse
}

// GetFuseOk returns a tuple with the Fuse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetFuseOk() (*bool, bool) {
	if o == nil || IsNil(o.Fuse) {
		return nil, false
	}
	return o.Fuse, true
}

// HasFuse returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasFuse() bool {
	if o != nil && !IsNil(o.Fuse) {
		return true
	}

	return false
}

// SetFuse gets a reference to the given bool and assigns it to the Fuse field.
func (o *CreateStorageRequestContent) SetFuse(v bool) {
	o.Fuse = &v
}

// GetIsMountpoint returns the IsMountpoint field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetIsMountpoint() string {
	if o == nil || IsNil(o.IsMountpoint) {
		var ret string
		return ret
	}
	return *o.IsMountpoint
}

// GetIsMountpointOk returns a tuple with the IsMountpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetIsMountpointOk() (*string, bool) {
	if o == nil || IsNil(o.IsMountpoint) {
		return nil, false
	}
	return o.IsMountpoint, true
}

// HasIsMountpoint returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasIsMountpoint() bool {
	if o != nil && !IsNil(o.IsMountpoint) {
		return true
	}

	return false
}

// SetIsMountpoint gets a reference to the given string and assigns it to the IsMountpoint field.
func (o *CreateStorageRequestContent) SetIsMountpoint(v string) {
	o.IsMountpoint = &v
}

// GetIscsiprovider returns the Iscsiprovider field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetIscsiprovider() string {
	if o == nil || IsNil(o.Iscsiprovider) {
		var ret string
		return ret
	}
	return *o.Iscsiprovider
}

// GetIscsiproviderOk returns a tuple with the Iscsiprovider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetIscsiproviderOk() (*string, bool) {
	if o == nil || IsNil(o.Iscsiprovider) {
		return nil, false
	}
	return o.Iscsiprovider, true
}

// HasIscsiprovider returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasIscsiprovider() bool {
	if o != nil && !IsNil(o.Iscsiprovider) {
		return true
	}

	return false
}

// SetIscsiprovider gets a reference to the given string and assigns it to the Iscsiprovider field.
func (o *CreateStorageRequestContent) SetIscsiprovider(v string) {
	o.Iscsiprovider = &v
}

// GetKeyring returns the Keyring field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetKeyring() string {
	if o == nil || IsNil(o.Keyring) {
		var ret string
		return ret
	}
	return *o.Keyring
}

// GetKeyringOk returns a tuple with the Keyring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetKeyringOk() (*string, bool) {
	if o == nil || IsNil(o.Keyring) {
		return nil, false
	}
	return o.Keyring, true
}

// HasKeyring returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasKeyring() bool {
	if o != nil && !IsNil(o.Keyring) {
		return true
	}

	return false
}

// SetKeyring gets a reference to the given string and assigns it to the Keyring field.
func (o *CreateStorageRequestContent) SetKeyring(v string) {
	o.Keyring = &v
}

// GetKrbd returns the Krbd field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetKrbd() bool {
	if o == nil || IsNil(o.Krbd) {
		var ret bool
		return ret
	}
	return *o.Krbd
}

// GetKrbdOk returns a tuple with the Krbd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetKrbdOk() (*bool, bool) {
	if o == nil || IsNil(o.Krbd) {
		return nil, false
	}
	return o.Krbd, true
}

// HasKrbd returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasKrbd() bool {
	if o != nil && !IsNil(o.Krbd) {
		return true
	}

	return false
}

// SetKrbd gets a reference to the given bool and assigns it to the Krbd field.
func (o *CreateStorageRequestContent) SetKrbd(v bool) {
	o.Krbd = &v
}

// GetLioTpg returns the LioTpg field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetLioTpg() string {
	if o == nil || IsNil(o.LioTpg) {
		var ret string
		return ret
	}
	return *o.LioTpg
}

// GetLioTpgOk returns a tuple with the LioTpg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetLioTpgOk() (*string, bool) {
	if o == nil || IsNil(o.LioTpg) {
		return nil, false
	}
	return o.LioTpg, true
}

// HasLioTpg returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasLioTpg() bool {
	if o != nil && !IsNil(o.LioTpg) {
		return true
	}

	return false
}

// SetLioTpg gets a reference to the given string and assigns it to the LioTpg field.
func (o *CreateStorageRequestContent) SetLioTpg(v string) {
	o.LioTpg = &v
}

// GetMasterPubkey returns the MasterPubkey field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetMasterPubkey() string {
	if o == nil || IsNil(o.MasterPubkey) {
		var ret string
		return ret
	}
	return *o.MasterPubkey
}

// GetMasterPubkeyOk returns a tuple with the MasterPubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetMasterPubkeyOk() (*string, bool) {
	if o == nil || IsNil(o.MasterPubkey) {
		return nil, false
	}
	return o.MasterPubkey, true
}

// HasMasterPubkey returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasMasterPubkey() bool {
	if o != nil && !IsNil(o.MasterPubkey) {
		return true
	}

	return false
}

// SetMasterPubkey gets a reference to the given string and assigns it to the MasterPubkey field.
func (o *CreateStorageRequestContent) SetMasterPubkey(v string) {
	o.MasterPubkey = &v
}

// GetMaxProtectedBackups returns the MaxProtectedBackups field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetMaxProtectedBackups() float32 {
	if o == nil || IsNil(o.MaxProtectedBackups) {
		var ret float32
		return ret
	}
	return *o.MaxProtectedBackups
}

// GetMaxProtectedBackupsOk returns a tuple with the MaxProtectedBackups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetMaxProtectedBackupsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxProtectedBackups) {
		return nil, false
	}
	return o.MaxProtectedBackups, true
}

// HasMaxProtectedBackups returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasMaxProtectedBackups() bool {
	if o != nil && !IsNil(o.MaxProtectedBackups) {
		return true
	}

	return false
}

// SetMaxProtectedBackups gets a reference to the given float32 and assigns it to the MaxProtectedBackups field.
func (o *CreateStorageRequestContent) SetMaxProtectedBackups(v float32) {
	o.MaxProtectedBackups = &v
}

// GetMkdir returns the Mkdir field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetMkdir() bool {
	if o == nil || IsNil(o.Mkdir) {
		var ret bool
		return ret
	}
	return *o.Mkdir
}

// GetMkdirOk returns a tuple with the Mkdir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetMkdirOk() (*bool, bool) {
	if o == nil || IsNil(o.Mkdir) {
		return nil, false
	}
	return o.Mkdir, true
}

// HasMkdir returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasMkdir() bool {
	if o != nil && !IsNil(o.Mkdir) {
		return true
	}

	return false
}

// SetMkdir gets a reference to the given bool and assigns it to the Mkdir field.
func (o *CreateStorageRequestContent) SetMkdir(v bool) {
	o.Mkdir = &v
}

// GetMonhost returns the Monhost field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetMonhost() string {
	if o == nil || IsNil(o.Monhost) {
		var ret string
		return ret
	}
	return *o.Monhost
}

// GetMonhostOk returns a tuple with the Monhost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetMonhostOk() (*string, bool) {
	if o == nil || IsNil(o.Monhost) {
		return nil, false
	}
	return o.Monhost, true
}

// HasMonhost returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasMonhost() bool {
	if o != nil && !IsNil(o.Monhost) {
		return true
	}

	return false
}

// SetMonhost gets a reference to the given string and assigns it to the Monhost field.
func (o *CreateStorageRequestContent) SetMonhost(v string) {
	o.Monhost = &v
}

// GetMountpoint returns the Mountpoint field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetMountpoint() string {
	if o == nil || IsNil(o.Mountpoint) {
		var ret string
		return ret
	}
	return *o.Mountpoint
}

// GetMountpointOk returns a tuple with the Mountpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetMountpointOk() (*string, bool) {
	if o == nil || IsNil(o.Mountpoint) {
		return nil, false
	}
	return o.Mountpoint, true
}

// HasMountpoint returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasMountpoint() bool {
	if o != nil && !IsNil(o.Mountpoint) {
		return true
	}

	return false
}

// SetMountpoint gets a reference to the given string and assigns it to the Mountpoint field.
func (o *CreateStorageRequestContent) SetMountpoint(v string) {
	o.Mountpoint = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *CreateStorageRequestContent) SetNamespace(v string) {
	o.Namespace = &v
}

// GetNocow returns the Nocow field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetNocow() float32 {
	if o == nil || IsNil(o.Nocow) {
		var ret float32
		return ret
	}
	return *o.Nocow
}

// GetNocowOk returns a tuple with the Nocow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetNocowOk() (*float32, bool) {
	if o == nil || IsNil(o.Nocow) {
		return nil, false
	}
	return o.Nocow, true
}

// HasNocow returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasNocow() bool {
	if o != nil && !IsNil(o.Nocow) {
		return true
	}

	return false
}

// SetNocow gets a reference to the given float32 and assigns it to the Nocow field.
func (o *CreateStorageRequestContent) SetNocow(v float32) {
	o.Nocow = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetNodes() string {
	if o == nil || IsNil(o.Nodes) {
		var ret string
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetNodesOk() (*string, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given string and assigns it to the Nodes field.
func (o *CreateStorageRequestContent) SetNodes(v string) {
	o.Nodes = &v
}

// GetNowritecache returns the Nowritecache field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetNowritecache() bool {
	if o == nil || IsNil(o.Nowritecache) {
		var ret bool
		return ret
	}
	return *o.Nowritecache
}

// GetNowritecacheOk returns a tuple with the Nowritecache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetNowritecacheOk() (*bool, bool) {
	if o == nil || IsNil(o.Nowritecache) {
		return nil, false
	}
	return o.Nowritecache, true
}

// HasNowritecache returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasNowritecache() bool {
	if o != nil && !IsNil(o.Nowritecache) {
		return true
	}

	return false
}

// SetNowritecache gets a reference to the given bool and assigns it to the Nowritecache field.
func (o *CreateStorageRequestContent) SetNowritecache(v bool) {
	o.Nowritecache = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetOptions() string {
	if o == nil || IsNil(o.Options) {
		var ret string
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetOptionsOk() (*string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given string and assigns it to the Options field.
func (o *CreateStorageRequestContent) SetOptions(v string) {
	o.Options = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateStorageRequestContent) SetPassword(v string) {
	o.Password = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *CreateStorageRequestContent) SetPath(v string) {
	o.Path = &v
}

// GetPool returns the Pool field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPool() string {
	if o == nil || IsNil(o.Pool) {
		var ret string
		return ret
	}
	return *o.Pool
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPoolOk() (*string, bool) {
	if o == nil || IsNil(o.Pool) {
		return nil, false
	}
	return o.Pool, true
}

// HasPool returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPool() bool {
	if o != nil && !IsNil(o.Pool) {
		return true
	}

	return false
}

// SetPool gets a reference to the given string and assigns it to the Pool field.
func (o *CreateStorageRequestContent) SetPool(v string) {
	o.Pool = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPort() float32 {
	if o == nil || IsNil(o.Port) {
		var ret float32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPortOk() (*float32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given float32 and assigns it to the Port field.
func (o *CreateStorageRequestContent) SetPort(v float32) {
	o.Port = &v
}

// GetPortal returns the Portal field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPortal() string {
	if o == nil || IsNil(o.Portal) {
		var ret string
		return ret
	}
	return *o.Portal
}

// GetPortalOk returns a tuple with the Portal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPortalOk() (*string, bool) {
	if o == nil || IsNil(o.Portal) {
		return nil, false
	}
	return o.Portal, true
}

// HasPortal returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPortal() bool {
	if o != nil && !IsNil(o.Portal) {
		return true
	}

	return false
}

// SetPortal gets a reference to the given string and assigns it to the Portal field.
func (o *CreateStorageRequestContent) SetPortal(v string) {
	o.Portal = &v
}

// GetPreallocation returns the Preallocation field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPreallocation() StoragePreallocation {
	if o == nil || IsNil(o.Preallocation) {
		var ret StoragePreallocation
		return ret
	}
	return *o.Preallocation
}

// GetPreallocationOk returns a tuple with the Preallocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPreallocationOk() (*StoragePreallocation, bool) {
	if o == nil || IsNil(o.Preallocation) {
		return nil, false
	}
	return o.Preallocation, true
}

// HasPreallocation returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPreallocation() bool {
	if o != nil && !IsNil(o.Preallocation) {
		return true
	}

	return false
}

// SetPreallocation gets a reference to the given StoragePreallocation and assigns it to the Preallocation field.
func (o *CreateStorageRequestContent) SetPreallocation(v StoragePreallocation) {
	o.Preallocation = &v
}

// GetPruneBackups returns the PruneBackups field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetPruneBackups() string {
	if o == nil || IsNil(o.PruneBackups) {
		var ret string
		return ret
	}
	return *o.PruneBackups
}

// GetPruneBackupsOk returns a tuple with the PruneBackups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetPruneBackupsOk() (*string, bool) {
	if o == nil || IsNil(o.PruneBackups) {
		return nil, false
	}
	return o.PruneBackups, true
}

// HasPruneBackups returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasPruneBackups() bool {
	if o != nil && !IsNil(o.PruneBackups) {
		return true
	}

	return false
}

// SetPruneBackups gets a reference to the given string and assigns it to the PruneBackups field.
func (o *CreateStorageRequestContent) SetPruneBackups(v string) {
	o.PruneBackups = &v
}

// GetSaferemove returns the Saferemove field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetSaferemove() bool {
	if o == nil || IsNil(o.Saferemove) {
		var ret bool
		return ret
	}
	return *o.Saferemove
}

// GetSaferemoveOk returns a tuple with the Saferemove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSaferemoveOk() (*bool, bool) {
	if o == nil || IsNil(o.Saferemove) {
		return nil, false
	}
	return o.Saferemove, true
}

// HasSaferemove returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasSaferemove() bool {
	if o != nil && !IsNil(o.Saferemove) {
		return true
	}

	return false
}

// SetSaferemove gets a reference to the given bool and assigns it to the Saferemove field.
func (o *CreateStorageRequestContent) SetSaferemove(v bool) {
	o.Saferemove = &v
}

// GetSaferemoveThroughput returns the SaferemoveThroughput field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetSaferemoveThroughput() string {
	if o == nil || IsNil(o.SaferemoveThroughput) {
		var ret string
		return ret
	}
	return *o.SaferemoveThroughput
}

// GetSaferemoveThroughputOk returns a tuple with the SaferemoveThroughput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSaferemoveThroughputOk() (*string, bool) {
	if o == nil || IsNil(o.SaferemoveThroughput) {
		return nil, false
	}
	return o.SaferemoveThroughput, true
}

// HasSaferemoveThroughput returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasSaferemoveThroughput() bool {
	if o != nil && !IsNil(o.SaferemoveThroughput) {
		return true
	}

	return false
}

// SetSaferemoveThroughput gets a reference to the given string and assigns it to the SaferemoveThroughput field.
func (o *CreateStorageRequestContent) SetSaferemoveThroughput(v string) {
	o.SaferemoveThroughput = &v
}

// GetServer returns the Server field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetServer() string {
	if o == nil || IsNil(o.Server) {
		var ret string
		return ret
	}
	return *o.Server
}

// GetServerOk returns a tuple with the Server field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetServerOk() (*string, bool) {
	if o == nil || IsNil(o.Server) {
		return nil, false
	}
	return o.Server, true
}

// HasServer returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasServer() bool {
	if o != nil && !IsNil(o.Server) {
		return true
	}

	return false
}

// SetServer gets a reference to the given string and assigns it to the Server field.
func (o *CreateStorageRequestContent) SetServer(v string) {
	o.Server = &v
}

// GetServer2 returns the Server2 field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetServer2() string {
	if o == nil || IsNil(o.Server2) {
		var ret string
		return ret
	}
	return *o.Server2
}

// GetServer2Ok returns a tuple with the Server2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetServer2Ok() (*string, bool) {
	if o == nil || IsNil(o.Server2) {
		return nil, false
	}
	return o.Server2, true
}

// HasServer2 returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasServer2() bool {
	if o != nil && !IsNil(o.Server2) {
		return true
	}

	return false
}

// SetServer2 gets a reference to the given string and assigns it to the Server2 field.
func (o *CreateStorageRequestContent) SetServer2(v string) {
	o.Server2 = &v
}

// GetShare returns the Share field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetShare() string {
	if o == nil || IsNil(o.Share) {
		var ret string
		return ret
	}
	return *o.Share
}

// GetShareOk returns a tuple with the Share field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetShareOk() (*string, bool) {
	if o == nil || IsNil(o.Share) {
		return nil, false
	}
	return o.Share, true
}

// HasShare returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasShare() bool {
	if o != nil && !IsNil(o.Share) {
		return true
	}

	return false
}

// SetShare gets a reference to the given string and assigns it to the Share field.
func (o *CreateStorageRequestContent) SetShare(v string) {
	o.Share = &v
}

// GetShared returns the Shared field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetShared() bool {
	if o == nil || IsNil(o.Shared) {
		var ret bool
		return ret
	}
	return *o.Shared
}

// GetSharedOk returns a tuple with the Shared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSharedOk() (*bool, bool) {
	if o == nil || IsNil(o.Shared) {
		return nil, false
	}
	return o.Shared, true
}

// HasShared returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasShared() bool {
	if o != nil && !IsNil(o.Shared) {
		return true
	}

	return false
}

// SetShared gets a reference to the given bool and assigns it to the Shared field.
func (o *CreateStorageRequestContent) SetShared(v bool) {
	o.Shared = &v
}

// GetSmbversion returns the Smbversion field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetSmbversion() StorageSMBVersion {
	if o == nil || IsNil(o.Smbversion) {
		var ret StorageSMBVersion
		return ret
	}
	return *o.Smbversion
}

// GetSmbversionOk returns a tuple with the Smbversion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSmbversionOk() (*StorageSMBVersion, bool) {
	if o == nil || IsNil(o.Smbversion) {
		return nil, false
	}
	return o.Smbversion, true
}

// HasSmbversion returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasSmbversion() bool {
	if o != nil && !IsNil(o.Smbversion) {
		return true
	}

	return false
}

// SetSmbversion gets a reference to the given StorageSMBVersion and assigns it to the Smbversion field.
func (o *CreateStorageRequestContent) SetSmbversion(v StorageSMBVersion) {
	o.Smbversion = &v
}

// GetSparse returns the Sparse field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetSparse() bool {
	if o == nil || IsNil(o.Sparse) {
		var ret bool
		return ret
	}
	return *o.Sparse
}

// GetSparseOk returns a tuple with the Sparse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSparseOk() (*bool, bool) {
	if o == nil || IsNil(o.Sparse) {
		return nil, false
	}
	return o.Sparse, true
}

// HasSparse returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasSparse() bool {
	if o != nil && !IsNil(o.Sparse) {
		return true
	}

	return false
}

// SetSparse gets a reference to the given bool and assigns it to the Sparse field.
func (o *CreateStorageRequestContent) SetSparse(v bool) {
	o.Sparse = &v
}

// GetSubdir returns the Subdir field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetSubdir() string {
	if o == nil || IsNil(o.Subdir) {
		var ret string
		return ret
	}
	return *o.Subdir
}

// GetSubdirOk returns a tuple with the Subdir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetSubdirOk() (*string, bool) {
	if o == nil || IsNil(o.Subdir) {
		return nil, false
	}
	return o.Subdir, true
}

// HasSubdir returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasSubdir() bool {
	if o != nil && !IsNil(o.Subdir) {
		return true
	}

	return false
}

// SetSubdir gets a reference to the given string and assigns it to the Subdir field.
func (o *CreateStorageRequestContent) SetSubdir(v string) {
	o.Subdir = &v
}

// GetTaggedOnly returns the TaggedOnly field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetTaggedOnly() bool {
	if o == nil || IsNil(o.TaggedOnly) {
		var ret bool
		return ret
	}
	return *o.TaggedOnly
}

// GetTaggedOnlyOk returns a tuple with the TaggedOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetTaggedOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.TaggedOnly) {
		return nil, false
	}
	return o.TaggedOnly, true
}

// HasTaggedOnly returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasTaggedOnly() bool {
	if o != nil && !IsNil(o.TaggedOnly) {
		return true
	}

	return false
}

// SetTaggedOnly gets a reference to the given bool and assigns it to the TaggedOnly field.
func (o *CreateStorageRequestContent) SetTaggedOnly(v bool) {
	o.TaggedOnly = &v
}

// GetThinpool returns the Thinpool field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetThinpool() string {
	if o == nil || IsNil(o.Thinpool) {
		var ret string
		return ret
	}
	return *o.Thinpool
}

// GetThinpoolOk returns a tuple with the Thinpool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetThinpoolOk() (*string, bool) {
	if o == nil || IsNil(o.Thinpool) {
		return nil, false
	}
	return o.Thinpool, true
}

// HasThinpool returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasThinpool() bool {
	if o != nil && !IsNil(o.Thinpool) {
		return true
	}

	return false
}

// SetThinpool gets a reference to the given string and assigns it to the Thinpool field.
func (o *CreateStorageRequestContent) SetThinpool(v string) {
	o.Thinpool = &v
}

// GetTransport returns the Transport field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetTransport() StorageTransport {
	if o == nil || IsNil(o.Transport) {
		var ret StorageTransport
		return ret
	}
	return *o.Transport
}

// GetTransportOk returns a tuple with the Transport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetTransportOk() (*StorageTransport, bool) {
	if o == nil || IsNil(o.Transport) {
		return nil, false
	}
	return o.Transport, true
}

// HasTransport returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasTransport() bool {
	if o != nil && !IsNil(o.Transport) {
		return true
	}

	return false
}

// SetTransport gets a reference to the given StorageTransport and assigns it to the Transport field.
func (o *CreateStorageRequestContent) SetTransport(v StorageTransport) {
	o.Transport = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *CreateStorageRequestContent) SetUsername(v string) {
	o.Username = &v
}

// GetVgname returns the Vgname field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetVgname() string {
	if o == nil || IsNil(o.Vgname) {
		var ret string
		return ret
	}
	return *o.Vgname
}

// GetVgnameOk returns a tuple with the Vgname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetVgnameOk() (*string, bool) {
	if o == nil || IsNil(o.Vgname) {
		return nil, false
	}
	return o.Vgname, true
}

// HasVgname returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasVgname() bool {
	if o != nil && !IsNil(o.Vgname) {
		return true
	}

	return false
}

// SetVgname gets a reference to the given string and assigns it to the Vgname field.
func (o *CreateStorageRequestContent) SetVgname(v string) {
	o.Vgname = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *CreateStorageRequestContent) GetVolume() string {
	if o == nil || IsNil(o.Volume) {
		var ret string
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStorageRequestContent) GetVolumeOk() (*string, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *CreateStorageRequestContent) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given string and assigns it to the Volume field.
func (o *CreateStorageRequestContent) SetVolume(v string) {
	o.Volume = &v
}

func (o CreateStorageRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStorageRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["storage"] = o.Storage
	toSerialize["type"] = o.Type
	if !IsNil(o.Authsupported) {
		toSerialize["authsupported"] = o.Authsupported
	}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	if !IsNil(o.Blocksize) {
		toSerialize["blocksize"] = o.Blocksize
	}
	if !IsNil(o.Bwlimit) {
		toSerialize["bwlimit"] = o.Bwlimit
	}
	if !IsNil(o.ComstarHg) {
		toSerialize["comstar_hg"] = o.ComstarHg
	}
	if !IsNil(o.ComstarTg) {
		toSerialize["comstar_tg"] = o.ComstarTg
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.DataPool) {
		toSerialize["data-pool"] = o.DataPool
	}
	if !IsNil(o.Disable) {
		toSerialize["disable"] = o.Disable
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.EncryptionKey) {
		toSerialize["encryption-key"] = o.EncryptionKey
	}
	if !IsNil(o.Export) {
		toSerialize["export"] = o.Export
	}
	if !IsNil(o.Fingerprint) {
		toSerialize["fingerprint"] = o.Fingerprint
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.FsName) {
		toSerialize["fs-name"] = o.FsName
	}
	if !IsNil(o.Fuse) {
		toSerialize["fuse"] = o.Fuse
	}
	if !IsNil(o.IsMountpoint) {
		toSerialize["is_mountpoint"] = o.IsMountpoint
	}
	if !IsNil(o.Iscsiprovider) {
		toSerialize["iscsiprovider"] = o.Iscsiprovider
	}
	if !IsNil(o.Keyring) {
		toSerialize["keyring"] = o.Keyring
	}
	if !IsNil(o.Krbd) {
		toSerialize["krbd"] = o.Krbd
	}
	if !IsNil(o.LioTpg) {
		toSerialize["lio_tpg"] = o.LioTpg
	}
	if !IsNil(o.MasterPubkey) {
		toSerialize["master-pubkey"] = o.MasterPubkey
	}
	if !IsNil(o.MaxProtectedBackups) {
		toSerialize["max-protected-backups"] = o.MaxProtectedBackups
	}
	if !IsNil(o.Mkdir) {
		toSerialize["mkdir"] = o.Mkdir
	}
	if !IsNil(o.Monhost) {
		toSerialize["monhost"] = o.Monhost
	}
	if !IsNil(o.Mountpoint) {
		toSerialize["mountpoint"] = o.Mountpoint
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Nocow) {
		toSerialize["nocow"] = o.Nocow
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.Nowritecache) {
		toSerialize["nowritecache"] = o.Nowritecache
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Pool) {
		toSerialize["pool"] = o.Pool
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Portal) {
		toSerialize["portal"] = o.Portal
	}
	if !IsNil(o.Preallocation) {
		toSerialize["preallocation"] = o.Preallocation
	}
	if !IsNil(o.PruneBackups) {
		toSerialize["prune-backups"] = o.PruneBackups
	}
	if !IsNil(o.Saferemove) {
		toSerialize["saferemove"] = o.Saferemove
	}
	if !IsNil(o.SaferemoveThroughput) {
		toSerialize["saferemove-throughput"] = o.SaferemoveThroughput
	}
	if !IsNil(o.Server) {
		toSerialize["server"] = o.Server
	}
	if !IsNil(o.Server2) {
		toSerialize["server2"] = o.Server2
	}
	if !IsNil(o.Share) {
		toSerialize["share"] = o.Share
	}
	if !IsNil(o.Shared) {
		toSerialize["shared"] = o.Shared
	}
	if !IsNil(o.Smbversion) {
		toSerialize["smbversion"] = o.Smbversion
	}
	if !IsNil(o.Sparse) {
		toSerialize["sparse"] = o.Sparse
	}
	if !IsNil(o.Subdir) {
		toSerialize["subdir"] = o.Subdir
	}
	if !IsNil(o.TaggedOnly) {
		toSerialize["tagged_only"] = o.TaggedOnly
	}
	if !IsNil(o.Thinpool) {
		toSerialize["thinpool"] = o.Thinpool
	}
	if !IsNil(o.Transport) {
		toSerialize["transport"] = o.Transport
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Vgname) {
		toSerialize["vgname"] = o.Vgname
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	return toSerialize, nil
}

type NullableCreateStorageRequestContent struct {
	value *CreateStorageRequestContent
	isSet bool
}

func (v NullableCreateStorageRequestContent) Get() *CreateStorageRequestContent {
	return v.value
}

func (v *NullableCreateStorageRequestContent) Set(val *CreateStorageRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStorageRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStorageRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStorageRequestContent(val *CreateStorageRequestContent) *NullableCreateStorageRequestContent {
	return &NullableCreateStorageRequestContent{value: val, isSet: true}
}

func (v NullableCreateStorageRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStorageRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


