/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the ListNodeStorageResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNodeStorageResponseContent{}

// ListNodeStorageResponseContent struct for ListNodeStorageResponseContent
type ListNodeStorageResponseContent struct {
	Data []NodeStorageSummary `json:"data"`
}

// NewListNodeStorageResponseContent instantiates a new ListNodeStorageResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNodeStorageResponseContent(data []NodeStorageSummary) *ListNodeStorageResponseContent {
	this := ListNodeStorageResponseContent{}
	this.Data = data
	return &this
}

// NewListNodeStorageResponseContentWithDefaults instantiates a new ListNodeStorageResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNodeStorageResponseContentWithDefaults() *ListNodeStorageResponseContent {
	this := ListNodeStorageResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListNodeStorageResponseContent) GetData() []NodeStorageSummary {
	if o == nil {
		var ret []NodeStorageSummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListNodeStorageResponseContent) GetDataOk() ([]NodeStorageSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListNodeStorageResponseContent) SetData(v []NodeStorageSummary) {
	o.Data = v
}

func (o ListNodeStorageResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNodeStorageResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListNodeStorageResponseContent struct {
	value *ListNodeStorageResponseContent
	isSet bool
}

func (v NullableListNodeStorageResponseContent) Get() *ListNodeStorageResponseContent {
	return v.value
}

func (v *NullableListNodeStorageResponseContent) Set(val *ListNodeStorageResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListNodeStorageResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListNodeStorageResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNodeStorageResponseContent(val *ListNodeStorageResponseContent) *NullableListNodeStorageResponseContent {
	return &NullableListNodeStorageResponseContent{value: val, isSet: true}
}

func (v NullableListNodeStorageResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNodeStorageResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


