/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the UpdateStorageVolumeRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStorageVolumeRequestContent{}

// UpdateStorageVolumeRequestContent struct for UpdateStorageVolumeRequestContent
type UpdateStorageVolumeRequestContent struct {
	// New notes for the volume
	Notes *string `json:"notes,omitempty"`
	// An integer used to represent a boolean. 0 is false, 1 is true.
	Protected float32 `json:"protected"`
}

// NewUpdateStorageVolumeRequestContent instantiates a new UpdateStorageVolumeRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStorageVolumeRequestContent(protected float32) *UpdateStorageVolumeRequestContent {
	this := UpdateStorageVolumeRequestContent{}
	this.Protected = protected
	return &this
}

// NewUpdateStorageVolumeRequestContentWithDefaults instantiates a new UpdateStorageVolumeRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStorageVolumeRequestContentWithDefaults() *UpdateStorageVolumeRequestContent {
	this := UpdateStorageVolumeRequestContent{}
	return &this
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *UpdateStorageVolumeRequestContent) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStorageVolumeRequestContent) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *UpdateStorageVolumeRequestContent) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *UpdateStorageVolumeRequestContent) SetNotes(v string) {
	o.Notes = &v
}

// GetProtected returns the Protected field value
func (o *UpdateStorageVolumeRequestContent) GetProtected() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Protected
}

// GetProtectedOk returns a tuple with the Protected field value
// and a boolean to check if the value has been set.
func (o *UpdateStorageVolumeRequestContent) GetProtectedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protected, true
}

// SetProtected sets field value
func (o *UpdateStorageVolumeRequestContent) SetProtected(v float32) {
	o.Protected = v
}

func (o UpdateStorageVolumeRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStorageVolumeRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	toSerialize["protected"] = o.Protected
	return toSerialize, nil
}

type NullableUpdateStorageVolumeRequestContent struct {
	value *UpdateStorageVolumeRequestContent
	isSet bool
}

func (v NullableUpdateStorageVolumeRequestContent) Get() *UpdateStorageVolumeRequestContent {
	return v.value
}

func (v *NullableUpdateStorageVolumeRequestContent) Set(val *UpdateStorageVolumeRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStorageVolumeRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStorageVolumeRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStorageVolumeRequestContent(val *UpdateStorageVolumeRequestContent) *NullableUpdateStorageVolumeRequestContent {
	return &NullableUpdateStorageVolumeRequestContent{value: val, isSet: true}
}

func (v NullableUpdateStorageVolumeRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStorageVolumeRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


