/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the ListNodeCertificatesResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNodeCertificatesResponseContent{}

// ListNodeCertificatesResponseContent struct for ListNodeCertificatesResponseContent
type ListNodeCertificatesResponseContent struct {
	Data []NodeCertificate `json:"data"`
}

// NewListNodeCertificatesResponseContent instantiates a new ListNodeCertificatesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNodeCertificatesResponseContent(data []NodeCertificate) *ListNodeCertificatesResponseContent {
	this := ListNodeCertificatesResponseContent{}
	this.Data = data
	return &this
}

// NewListNodeCertificatesResponseContentWithDefaults instantiates a new ListNodeCertificatesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNodeCertificatesResponseContentWithDefaults() *ListNodeCertificatesResponseContent {
	this := ListNodeCertificatesResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListNodeCertificatesResponseContent) GetData() []NodeCertificate {
	if o == nil {
		var ret []NodeCertificate
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListNodeCertificatesResponseContent) GetDataOk() ([]NodeCertificate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListNodeCertificatesResponseContent) SetData(v []NodeCertificate) {
	o.Data = v
}

func (o ListNodeCertificatesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNodeCertificatesResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListNodeCertificatesResponseContent struct {
	value *ListNodeCertificatesResponseContent
	isSet bool
}

func (v NullableListNodeCertificatesResponseContent) Get() *ListNodeCertificatesResponseContent {
	return v.value
}

func (v *NullableListNodeCertificatesResponseContent) Set(val *ListNodeCertificatesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListNodeCertificatesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListNodeCertificatesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNodeCertificatesResponseContent(val *ListNodeCertificatesResponseContent) *NullableListNodeCertificatesResponseContent {
	return &NullableListNodeCertificatesResponseContent{value: val, isSet: true}
}

func (v NullableListNodeCertificatesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNodeCertificatesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


