/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the ListUsbDevicesResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListUsbDevicesResponseContent{}

// ListUsbDevicesResponseContent struct for ListUsbDevicesResponseContent
type ListUsbDevicesResponseContent struct {
	Data []UsbDeviceSummary `json:"data"`
}

// NewListUsbDevicesResponseContent instantiates a new ListUsbDevicesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListUsbDevicesResponseContent(data []UsbDeviceSummary) *ListUsbDevicesResponseContent {
	this := ListUsbDevicesResponseContent{}
	this.Data = data
	return &this
}

// NewListUsbDevicesResponseContentWithDefaults instantiates a new ListUsbDevicesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListUsbDevicesResponseContentWithDefaults() *ListUsbDevicesResponseContent {
	this := ListUsbDevicesResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *ListUsbDevicesResponseContent) GetData() []UsbDeviceSummary {
	if o == nil {
		var ret []UsbDeviceSummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListUsbDevicesResponseContent) GetDataOk() ([]UsbDeviceSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListUsbDevicesResponseContent) SetData(v []UsbDeviceSummary) {
	o.Data = v
}

func (o ListUsbDevicesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListUsbDevicesResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListUsbDevicesResponseContent struct {
	value *ListUsbDevicesResponseContent
	isSet bool
}

func (v NullableListUsbDevicesResponseContent) Get() *ListUsbDevicesResponseContent {
	return v.value
}

func (v *NullableListUsbDevicesResponseContent) Set(val *ListUsbDevicesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListUsbDevicesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListUsbDevicesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListUsbDevicesResponseContent(val *ListUsbDevicesResponseContent) *NullableListUsbDevicesResponseContent {
	return &NullableListUsbDevicesResponseContent{value: val, isSet: true}
}

func (v NullableListUsbDevicesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListUsbDevicesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


