/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the GetClusterTotemSettingsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClusterTotemSettingsResponseContent{}

// GetClusterTotemSettingsResponseContent struct for GetClusterTotemSettingsResponseContent
type GetClusterTotemSettingsResponseContent struct {
	Data *TotemSummary `json:"data,omitempty"`
}

// NewGetClusterTotemSettingsResponseContent instantiates a new GetClusterTotemSettingsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterTotemSettingsResponseContent() *GetClusterTotemSettingsResponseContent {
	this := GetClusterTotemSettingsResponseContent{}
	return &this
}

// NewGetClusterTotemSettingsResponseContentWithDefaults instantiates a new GetClusterTotemSettingsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterTotemSettingsResponseContentWithDefaults() *GetClusterTotemSettingsResponseContent {
	this := GetClusterTotemSettingsResponseContent{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetClusterTotemSettingsResponseContent) GetData() TotemSummary {
	if o == nil || IsNil(o.Data) {
		var ret TotemSummary
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterTotemSettingsResponseContent) GetDataOk() (*TotemSummary, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetClusterTotemSettingsResponseContent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TotemSummary and assigns it to the Data field.
func (o *GetClusterTotemSettingsResponseContent) SetData(v TotemSummary) {
	o.Data = &v
}

func (o GetClusterTotemSettingsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClusterTotemSettingsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetClusterTotemSettingsResponseContent struct {
	value *GetClusterTotemSettingsResponseContent
	isSet bool
}

func (v NullableGetClusterTotemSettingsResponseContent) Get() *GetClusterTotemSettingsResponseContent {
	return v.value
}

func (v *NullableGetClusterTotemSettingsResponseContent) Set(val *GetClusterTotemSettingsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterTotemSettingsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterTotemSettingsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterTotemSettingsResponseContent(val *GetClusterTotemSettingsResponseContent) *NullableGetClusterTotemSettingsResponseContent {
	return &NullableGetClusterTotemSettingsResponseContent{value: val, isSet: true}
}

func (v NullableGetClusterTotemSettingsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterTotemSettingsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


