/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// checks if the GetVirtualMachineTimeResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVirtualMachineTimeResponseContent{}

// GetVirtualMachineTimeResponseContent struct for GetVirtualMachineTimeResponseContent
type GetVirtualMachineTimeResponseContent struct {
	Data GetTimeResult `json:"data"`
}

// NewGetVirtualMachineTimeResponseContent instantiates a new GetVirtualMachineTimeResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVirtualMachineTimeResponseContent(data GetTimeResult) *GetVirtualMachineTimeResponseContent {
	this := GetVirtualMachineTimeResponseContent{}
	this.Data = data
	return &this
}

// NewGetVirtualMachineTimeResponseContentWithDefaults instantiates a new GetVirtualMachineTimeResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVirtualMachineTimeResponseContentWithDefaults() *GetVirtualMachineTimeResponseContent {
	this := GetVirtualMachineTimeResponseContent{}
	return &this
}

// GetData returns the Data field value
func (o *GetVirtualMachineTimeResponseContent) GetData() GetTimeResult {
	if o == nil {
		var ret GetTimeResult
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetVirtualMachineTimeResponseContent) GetDataOk() (*GetTimeResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetVirtualMachineTimeResponseContent) SetData(v GetTimeResult) {
	o.Data = v
}

func (o GetVirtualMachineTimeResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVirtualMachineTimeResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGetVirtualMachineTimeResponseContent struct {
	value *GetVirtualMachineTimeResponseContent
	isSet bool
}

func (v NullableGetVirtualMachineTimeResponseContent) Get() *GetVirtualMachineTimeResponseContent {
	return v.value
}

func (v *NullableGetVirtualMachineTimeResponseContent) Set(val *GetVirtualMachineTimeResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVirtualMachineTimeResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVirtualMachineTimeResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVirtualMachineTimeResponseContent(val *GetVirtualMachineTimeResponseContent) *NullableGetVirtualMachineTimeResponseContent {
	return &NullableGetVirtualMachineTimeResponseContent{value: val, isSet: true}
}

func (v NullableGetVirtualMachineTimeResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVirtualMachineTimeResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


