/*
Proxmox

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package proxmox

import (
	"encoding/json"
)

// MemoryBlockSummary struct for MemoryBlockSummary
type MemoryBlockSummary struct {
	Online *bool `json:"online,omitempty"`
	CanOffline *bool `json:"can-offline,omitempty"`
	PhysIndex *float32 `json:"phys-index,omitempty"`
}

// NewMemoryBlockSummary instantiates a new MemoryBlockSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryBlockSummary() *MemoryBlockSummary {
	this := MemoryBlockSummary{}
	return &this
}

// NewMemoryBlockSummaryWithDefaults instantiates a new MemoryBlockSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryBlockSummaryWithDefaults() *MemoryBlockSummary {
	this := MemoryBlockSummary{}
	return &this
}

// GetOnline returns the Online field value if set, zero value otherwise.
func (o *MemoryBlockSummary) GetOnline() bool {
	if o == nil || isNil(o.Online) {
		var ret bool
		return ret
	}
	return *o.Online
}

// GetOnlineOk returns a tuple with the Online field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryBlockSummary) GetOnlineOk() (*bool, bool) {
	if o == nil || isNil(o.Online) {
    return nil, false
	}
	return o.Online, true
}

// HasOnline returns a boolean if a field has been set.
func (o *MemoryBlockSummary) HasOnline() bool {
	if o != nil && !isNil(o.Online) {
		return true
	}

	return false
}

// SetOnline gets a reference to the given bool and assigns it to the Online field.
func (o *MemoryBlockSummary) SetOnline(v bool) {
	o.Online = &v
}

// GetCanOffline returns the CanOffline field value if set, zero value otherwise.
func (o *MemoryBlockSummary) GetCanOffline() bool {
	if o == nil || isNil(o.CanOffline) {
		var ret bool
		return ret
	}
	return *o.CanOffline
}

// GetCanOfflineOk returns a tuple with the CanOffline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryBlockSummary) GetCanOfflineOk() (*bool, bool) {
	if o == nil || isNil(o.CanOffline) {
    return nil, false
	}
	return o.CanOffline, true
}

// HasCanOffline returns a boolean if a field has been set.
func (o *MemoryBlockSummary) HasCanOffline() bool {
	if o != nil && !isNil(o.CanOffline) {
		return true
	}

	return false
}

// SetCanOffline gets a reference to the given bool and assigns it to the CanOffline field.
func (o *MemoryBlockSummary) SetCanOffline(v bool) {
	o.CanOffline = &v
}

// GetPhysIndex returns the PhysIndex field value if set, zero value otherwise.
func (o *MemoryBlockSummary) GetPhysIndex() float32 {
	if o == nil || isNil(o.PhysIndex) {
		var ret float32
		return ret
	}
	return *o.PhysIndex
}

// GetPhysIndexOk returns a tuple with the PhysIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryBlockSummary) GetPhysIndexOk() (*float32, bool) {
	if o == nil || isNil(o.PhysIndex) {
    return nil, false
	}
	return o.PhysIndex, true
}

// HasPhysIndex returns a boolean if a field has been set.
func (o *MemoryBlockSummary) HasPhysIndex() bool {
	if o != nil && !isNil(o.PhysIndex) {
		return true
	}

	return false
}

// SetPhysIndex gets a reference to the given float32 and assigns it to the PhysIndex field.
func (o *MemoryBlockSummary) SetPhysIndex(v float32) {
	o.PhysIndex = &v
}

func (o MemoryBlockSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Online) {
		toSerialize["online"] = o.Online
	}
	if !isNil(o.CanOffline) {
		toSerialize["can-offline"] = o.CanOffline
	}
	if !isNil(o.PhysIndex) {
		toSerialize["phys-index"] = o.PhysIndex
	}
	return json.Marshal(toSerialize)
}

type NullableMemoryBlockSummary struct {
	value *MemoryBlockSummary
	isSet bool
}

func (v NullableMemoryBlockSummary) Get() *MemoryBlockSummary {
	return v.value
}

func (v *NullableMemoryBlockSummary) Set(val *MemoryBlockSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryBlockSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryBlockSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryBlockSummary(val *MemoryBlockSummary) *NullableMemoryBlockSummary {
	return &NullableMemoryBlockSummary{value: val, isSet: true}
}

func (v NullableMemoryBlockSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryBlockSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


